import{EdgePgSemanticError as o}from"./semantic-error";import{physicalRelationName as S}from"./relation-identity";import{parsePostgresSql as D}from"./postgres-parser";import{canonicalRoutineTypeName as $,resolveRoutineTypeOid as w}from"./routine-types";import{ensureRoutineCatalogSchema as M,routineDependencyDropStatementsForOid as U}from"./routines";import{assertSchemaPrivilege as P}from"./roles";async function _e(t){if(!/^\s*(?:CREATE|ALTER|DROP)\s+AGGREGATE\b/iu.test(t))return;const e=g(await D(t)),n=Array.isArray(e?.stmts)?e.stmts:[];if(n.length!==1)throw new o("42601","AGGREGATE DDL requires one statement");const r=g(g(n[0])?.stmt),a=g(r?.DefineStmt);if(a?.kind==="OBJECT_AGGREGATE"){const i=j(a.defnames),c=Y(a.args);if(!i||c.length!==1)throw new o("0A000","EdgePG Stage1 aggregates require exactly one ordinary input argument");const _=Array.isArray(a.definition)?a.definition.map(m=>g(g(m)?.DefElem)).filter(Boolean):[],u=new Set(["sfunc","stype","initcond"]),d=_.find(m=>!u.has(String(m?.defname||"").toLowerCase()));if(d)throw new o("0A000",`CREATE AGGREGATE option ${String(d.defname).toUpperCase()} has no EdgePG transition executor`);const p=m=>_.find(F=>String(F?.defname).toLowerCase()===m),y=Z(p("sfunc")?.arg),f=R(p("stype")?.arg);if(!y||!f)throw new o("42601","SFUNC and STYPE are required");const E=g(p("initcond")?.arg),h=typeof g(E?.String)?.sval=="string"?String(g(E?.String)?.sval):typeof E?.sval=="string"?E.sval:null;return{action:"create",...i,inputType:c[0],transitionFunction:y,stateType:f,initcond:h,definition:t.trim().replace(/;+\s*$/u,"")}}const s=g(r?.RenameStmt);if(s?.renameType==="OBJECT_AGGREGATE"){const i=b(g(s.object)?.ObjectWithArgs);if(!i||typeof s.newname!="string")throw new o("42601","invalid ALTER AGGREGATE identity");return{action:"rename",...i,newName:s.newname,newPhysicalName:S(i.schema,s.newname)}}const l=g(r?.DropStmt);if(l?.removeType==="OBJECT_AGGREGATE"){const i=Array.isArray(l.objects)?l.objects.map(c=>b(g(c)?.ObjectWithArgs)).filter(Boolean):[];if(!i.length||i.length!==l.objects.length)throw new o("42601","invalid DROP AGGREGATE identity");return{action:"drop",targets:i,ifExists:l.missing_ok===!0,cascade:l.behavior==="DROP_CASCADE"}}throw new o("0A000","this AGGREGATE DDL variant has no EdgePG transition executor")}async function ce(t,e,n="edgepg"){return await L(t),e.action==="create"?W(t,e,n):e.action==="rename"?H(t,e,n):J(t,e,n)}async function L(t){await M(t),await t.prepare(`CREATE TABLE IF NOT EXISTS __edgepg_aggregates(
    aggregate_oid INTEGER PRIMARY KEY,
    transition_oid INTEGER NOT NULL,
    transition_name TEXT NOT NULL,
    transition_type_oid INTEGER NOT NULL,
    input_type_oid INTEGER NOT NULL,
    initcond TEXT,
    transition_strict INTEGER NOT NULL,
    executor_kind TEXT NOT NULL CHECK(executor_kind IN ('sum-strict','sum-coalesce'))
  )`).run()}async function W(t,e,n){await P(t,n,e.schema,"CREATE");const r=await w(t,e.inputType),a=await w(t,e.stateType);if(r!==a)throw new o("0A000","EdgePG Stage1 aggregate transition execution requires STYPE to equal the input type");if(await N(t,e.schema,e.name,r))throw new o("42723",`function "${e.name}" already exists with same argument types`,409);if(await G(t,e.schema,e.name,r))throw new o("42723",`function "${e.name}" already exists with same argument types`,409);const i=await B(t,e,a,r);V(e.initcond,a);const c=C(e.inputType),_=new Date().toISOString();return await t.batch([t.prepare(`INSERT INTO __edgepg_routines(
      routine_oid,name,display_name,routine_kind,argument_names_json,argument_types_json,return_type,
      language,declared_language,expression_template,plpgsql_ast_json,definition,updated_at,schema_name,
      routine_name,owner_name,input_argument_types_json,input_argument_type_oids_json,all_argument_types_json,
      all_argument_type_oids_json,argument_modes_json,argument_defaults_json,input_default_count,
      variadic_type_oid,return_type_oid,legacy_identity_unresolved,routine_acl_initialized,
      identity_arguments_text,arguments_text,result_text)
      VALUES((SELECT next_oid FROM __edgepg_routine_oid_allocator),?1,?2,'function','[]',?3,?4,
        'internal','internal','',NULL,?5,?6,?7,?8,?9,?3,?10,?3,?10,'["in"]','[null]',0,0,?11,0,1,?12,?12,?4)`).bind(e.physicalName,`${e.schema}.${e.name}`,JSON.stringify([c]),C(e.stateType),e.definition,_,e.schema,e.name,n,JSON.stringify([r]),a,c),t.prepare(`INSERT INTO __edgepg_aggregates(aggregate_oid,transition_oid,transition_name,
      transition_type_oid,input_type_oid,initcond,transition_strict,executor_kind)
      VALUES((SELECT next_oid FROM __edgepg_routine_oid_allocator),?1,?2,?3,?4,?5,?6,?7)`).bind(i.oid,i.name,a,r,e.initcond,i.strict?1:0,i.executor),t.prepare(`INSERT INTO __edgepg_routine_privileges(routine_oid,grantor,grantee,privilege_type,is_grantable)
      VALUES((SELECT next_oid FROM __edgepg_routine_oid_allocator),?1,?1,'EXECUTE',0)`).bind(n),t.prepare(`INSERT INTO __edgepg_routine_privileges(routine_oid,grantor,grantee,privilege_type,is_grantable)
      VALUES((SELECT next_oid FROM __edgepg_routine_oid_allocator),?1,'public','EXECUTE',0)`).bind(n),t.prepare("UPDATE __edgepg_routine_oid_allocator SET next_oid=next_oid+1 WHERE id=1")]),{command:"CREATE AGGREGATE",rowCount:0}}async function H(t,e,n){const r=await w(t,e.inputType),a=await X(t,e.schema,e.name,r);if(await I(t,a,n),await G(t,e.schema,e.newName,r))throw new o("42723",`function "${e.newName}" already exists with same argument types`,409);return await t.prepare(`UPDATE __edgepg_routines SET name=?2,display_name=?3,routine_name=?4,
    definition=replace(definition,?5,?6),updated_at=?7 WHERE routine_oid=?1`).bind(a.routine_oid,e.newPhysicalName,`${e.schema}.${e.newName}`,e.newName,`${e.schema}.${e.name}`,`${e.schema}.${e.newName}`,new Date().toISOString()).run(),{command:"ALTER AGGREGATE",rowCount:0}}async function J(t,e,n){const r=[],a=[];for(const i of e.targets){try{await A(t,i.schema)}catch(u){if(!e.ifExists||!(u instanceof o)||u.code!=="3F000")throw u;a.push({severity:"NOTICE",code:"00000",message:`${u.message}, skipping`});continue}let c;try{i.inputType!=="*"&&await v(t,i.inputType),c=i.inputType==="*"?0:await w(t,i.inputType)}catch(u){if(!e.ifExists||!(u instanceof o)||!["3F000","42704"].includes(u.code))throw u;const d=u.code==="3F000"?u.message:`type "${i.inputType.split(".").at(-1)||i.inputType}" does not exist`;a.push({severity:"NOTICE",code:"00000",message:`${d}, skipping`});continue}const _=await N(t,i.schema,i.name,c);if(!_){if(!e.ifExists)throw new o("42883",`${x(i,!1)} does not exist`,404);a.push({severity:"NOTICE",code:"00000",message:`${x(i,!0)} does not exist, skipping`});continue}await I(t,_,n),r.some(u=>u.routine_oid===_.routine_oid)||r.push(_)}const s=[],l=await q(t);for(const i of r)s.push(...await U(t,i,e.cascade,"aggregate")),l&&s.push(t.prepare(`DELETE FROM __edgepg_comments
      WHERE object_type='OBJECT_AGGREGATE' AND identity_json=?1`).bind(JSON.stringify([String(i.routine_oid)]))),s.push(t.prepare("DELETE FROM __edgepg_aggregates WHERE aggregate_oid=?1").bind(i.routine_oid)),s.push(t.prepare("DELETE FROM __edgepg_routine_privileges WHERE routine_oid=?1").bind(i.routine_oid)),s.push(t.prepare("DELETE FROM __edgepg_routines WHERE routine_oid=?1").bind(i.routine_oid));return s.length&&await t.batch(s),{command:"DROP AGGREGATE",rowCount:0,...a.length?{notices:a}:{}}}async function v(t,e){const n=$(e).name.split(".").at(-2);!n||n==="pg_catalog"||await A(t,n)}function x(t,e){const n=t.explicitlyQualified?`${t.schema}.`:"";if(t.inputType==="*")return`aggregate ${n}${t.name}(${e?"":"*"})`;const r=e?t.inputType.replaceAll('"',"").replace(/\s+/gu,""):C(t.inputType);return`aggregate ${n}${t.name}(${r})`}async function q(t){return!!await t.prepare("SELECT 1 AS present FROM sqlite_master WHERE type='table' AND name='__edgepg_comments'").first()}async function le(t,e,n,r,a){await L(t);const s=(await t.prepare(`SELECT routine.* FROM __edgepg_routines AS routine
    JOIN __edgepg_aggregates AS aggregate ON aggregate.aggregate_oid=routine.routine_oid
    WHERE routine.name=?1`).bind(e.physicalName).all()).results;if(!s.length)return;if(n.length!==1)throw new o("42883",`aggregate ${e.name} does not exist`,404);const l=await ee(t,n[0].source,a),i=s.filter(f=>{const E=re(f.input_argument_type_oids_json)[0];return!l||l===E});if(i.length!==1)throw i.length?new o("42725",`aggregate ${e.name} is not unique`):new o("42883",`aggregate ${e.name} does not exist`,404);const c=i[0];await z(t,c,r);const _=await t.prepare("SELECT * FROM __edgepg_aggregates WHERE aggregate_oid=?1").bind(c.routine_oid).first();if(!_)throw new o("XX000",`aggregate metadata is missing for ${e.name}`);const u=te(n[0].source),p=`SUM(${_.executor_kind==="sum-coalesce"?`COALESCE((${u}),0)`:`(${u})`})`,y=_.initcond===null?p:`(CAST(${ie(_.initcond)} AS ${ne(_.transition_type_oid)})+COALESCE(${p},0))`;return{start:e.start,end:e.end,replacement:y}}async function B(t,e,n,r){const a=K(e.transitionFunction,e.schema),s=k(e.transitionFunction.includes(".")?a.schema:"pg_catalog",a.name,n,r);if(s)return s;await A(t,a.schema);const l=S(a.schema,a.name),i=await t.prepare(`SELECT * FROM __edgepg_routines WHERE name=?1 AND routine_kind='function'
    AND input_argument_type_oids_json=?2`).bind(l,JSON.stringify([n,r])).first();if(!i)throw new o("42883",`function ${a.schema}.${a.name}(${T(n)}, ${T(r)}) does not exist`,404);if(Number(i.return_type_oid)!==n)throw new o("42P13","return type of transition function must match aggregate transition type");const c=/\bSTRICT\b|\bRETURNS\s+NULL\s+ON\s+NULL\s+INPUT\b/iu.test(i.definition),_=i.expression_template.replace(/\s+/gu,"").replace(/^\((.*)\)$/u,"$1").toLowerCase(),u=new Set(["__edgepg_arg_0__+__edgepg_arg_1__","__edgepg_arg_1__+__edgepg_arg_0__"]),d=new Set(["coalesce(__edgepg_arg_0__,0)+coalesce(__edgepg_arg_1__,0)","coalesce(__edgepg_arg_1__,0)+coalesce(__edgepg_arg_0__,0)"]),p=u.has(_)&&c?"sum-strict":d.has(_)&&!c?"sum-coalesce":void 0;if(!p)throw new o("0A000",`transition function ${e.transitionFunction} is not reducible by the EdgePG Stage1 transition executor`);return{oid:i.routine_oid,name:`${a.schema}.${a.name}`,strict:c,executor:p}}function k(t,e,n,r){if(n!==r)return;const s={int4pl:{oid:177,type:23},int8pl:{oid:463,type:20},numeric_add:{oid:1724,type:1700}}[e.toLowerCase()];if(!(!s||!["pg_catalog","public"].includes(t)||s.type!==n))return{oid:s.oid,name:`pg_catalog.${e}`,strict:!0,executor:"sum-strict"}}async function N(t,e,n,r){return t.prepare(`SELECT routine.* FROM __edgepg_routines AS routine
    JOIN __edgepg_aggregates AS aggregate ON aggregate.aggregate_oid=routine.routine_oid
    WHERE routine.schema_name=?1 AND routine.routine_name=?2 AND routine.input_argument_type_oids_json=?3`).bind(e,n,JSON.stringify([r])).first()}async function G(t,e,n,r){return t.prepare(`SELECT * FROM __edgepg_routines WHERE schema_name=?1 AND routine_name=?2
    AND input_argument_type_oids_json=?3`).bind(e,n,JSON.stringify([r])).first()}async function X(t,e,n,r){await A(t,e);const a=await N(t,e,n,r);if(!a)throw new o("42883",`aggregate ${e}.${n}(${T(r)}) does not exist`,404);return a}async function A(t,e){if(!await t.prepare("SELECT 1 AS present FROM __edgepg_schemas WHERE name=?1").bind(e).first())throw new o("3F000",`schema "${e}" does not exist`,404)}async function I(t,e,n){if(e.owner_name===n||n==="postgres"||(await t.prepare("SELECT is_superuser FROM __edgepg_roles WHERE name=?1").bind(n).first().catch(()=>null))?.is_superuser)return;if(!await t.prepare(`WITH RECURSIVE roles(name) AS (
    SELECT role_name FROM __edgepg_role_memberships WHERE member_name=?1 AND set_option=1
    UNION SELECT membership.role_name FROM __edgepg_role_memberships AS membership
      JOIN roles ON roles.name=membership.member_name WHERE membership.set_option=1)
    SELECT 1 AS present FROM roles WHERE name=?2 LIMIT 1`).bind(n,e.owner_name).first().catch(()=>null))throw new o("42501",`must be owner of aggregate ${e.display_name}`,403)}async function z(t,e,n){if(e.owner_name===n||n==="postgres"||(await t.prepare("SELECT is_superuser FROM __edgepg_roles WHERE name=?1").bind(n).first().catch(()=>null))?.is_superuser||!e.routine_acl_initialized)return;if(!await t.prepare(`WITH RECURSIVE inherited(name) AS (
    SELECT ?2 UNION SELECT membership.role_name FROM __edgepg_role_memberships AS membership
      JOIN inherited ON inherited.name=membership.member_name WHERE membership.inherit_option=1)
    SELECT 1 AS present FROM __edgepg_routine_privileges WHERE routine_oid=?1 AND privilege_type='EXECUTE'
      AND (grantee='public' OR grantee IN (SELECT name FROM inherited)) LIMIT 1`).bind(e.routine_oid,n).first())throw new o("42501",`permission denied for aggregate ${e.routine_name}`,403)}function V(t,e){if(t!==null){if([20,21,23].includes(e)&&!/^[+-]?\d+$/u.test(t))throw new o("22P02",`invalid input syntax for type ${T(e)}: "${t}"`);if([700,701,1700].includes(e)&&!/^[+-]?(?:\d+(?:\.\d*)?|\.\d+)(?:e[+-]?\d+)?$/iu.test(t))throw new o("22P02",`invalid input syntax for type ${T(e)}: "${t}"`)}}function Y(t){const e=Array.isArray(t)?t:[],n=g(e[0])?.List;return(Array.isArray(g(n)?.items)?g(n).items:[]).map(a=>R(g(g(a)?.FunctionParameter)?.argType)).filter(Boolean)}function b(t){if(!t)return;const e=j(t.objname),n=Array.isArray(t.objargs)?t.objargs.map(R).filter(Boolean):[];if(!(!e||n.length>1))return{...e,inputType:n[0]||"*"}}function j(t){const e=O(t);if(!e.length)return;const n=e.at(-1),r=e.length>1?e.at(-2):"public";return{schema:r,name:n,physicalName:S(r,n),explicitlyQualified:e.length>1}}function Z(t){const e=O(g(t)?.TypeName?.names);return e.length?e.join("."):void 0}function R(t){const e=g(t)?.TypeName||t,n=O(g(e)?.names);if(!n.length)return;const r=Array.isArray(g(e)?.arrayBounds)?g(e).arrayBounds.length:0;return`${n.join(".")}${"[]".repeat(r)}`}function O(t){return Array.isArray(t)?t.map(e=>g(g(e)?.String)?.sval).filter(e=>typeof e=="string"):[]}function K(t,e){const n=t.replaceAll('"',"").split(".");return{schema:n.length>1?n.at(-2):e,name:n.at(-1)}}function C(t){const e=$(t);return`${e.name}${e.array?"[]":""}`}function T(t){return{20:"bigint",21:"smallint",23:"integer",700:"real",701:"double precision",1700:"numeric"}[t]||String(t)}function Q(t){const e=t.match(/::\s*(?:pg_catalog\.)?(bigint|int8|integer|int4|smallint|int2|numeric|decimal|real|float4|float8|double\s+precision)\s*$/iu)?.[1]?.toLowerCase();return e?["bigint","int8"].includes(e)?20:["smallint","int2"].includes(e)?21:["integer","int4"].includes(e)?23:["real","float4"].includes(e)?700:["float8","double precision"].includes(e)?701:1700:0}async function ee(t,e,n){const r=Q(e);if(r)return r;const s=e.trim().replace(/::\s*[^:]+$/u,"").trim().match(/^(?:"((?:[^"]|"")+)"|([A-Za-z_][\w$]*))(?:\.(?:"((?:[^"]|"")+)"|([A-Za-z_][\w$]*)))?(?:\.(?:"((?:[^"]|"")+)"|([A-Za-z_][\w$]*)))?$/u);if(!s)return 0;const l=[s[1]??s[2],s[3]??s[4],s[5]??s[6]].filter(p=>typeof p=="string").map(p=>p.replaceAll('""','"')),i=l.at(-1);if(!i)return 0;const c=n||(l.length>1?l.slice(0,-1).join("."):void 0);let _=[];try{_=(await t.prepare(`SELECT physical_name,
      COALESCE(current_columns_json,columns_json) AS columns_json,
      COALESCE(current_pg_types_json,pg_types_json) AS pg_types_json
      FROM __edgepg_pg_tables`).all()).results}catch(p){if(/no such table/iu.test(p instanceof Error?p.message:String(p)))return 0;throw p}const u=[];for(const p of _){if(c){const h=p.physical_name.toLowerCase(),m=c.toLowerCase();if(h!==m&&!h.endsWith(`__${m.split(".").at(-1)}`)&&!h.endsWith(`_${m.split(".").at(-1)}`))continue}let y,f;try{y=JSON.parse(p.columns_json),f=JSON.parse(p.pg_types_json)}catch{continue}if(!Array.isArray(y)||!Array.isArray(f))continue;const E=y.findIndex(h=>typeof h=="string"&&h.toLowerCase()===i.toLowerCase());if(!(E<0||typeof f[E]!="string"))try{u.push(await w(t,f[E]))}catch{}}const d=[...new Set(u)];return d.length===1?d[0]:0}function te(t){return t.replace(/(.+?)::\s*(?:pg_catalog\.)?(?:bigint|int8|integer|int4|smallint|int2)\s*$/iu,"CAST(($1) AS INTEGER)").replace(/(.+?)::\s*(?:pg_catalog\.)?(?:numeric|decimal|real|float4|float8|double\s+precision)\s*$/iu,"CAST(($1) AS REAL)")}function ne(t){return[20,21,23].includes(t)?"INTEGER":"REAL"}function ie(t){return`'${t.replaceAll("'","''")}'`}function re(t){try{const e=JSON.parse(t);return Array.isArray(e)?e.map(Number):[]}catch{return[]}}function g(t){return t&&typeof t=="object"?t:null}export{le as aggregateCallRewrite,L as ensureAggregateCatalogSchema,ce as executeAggregateCommand,_e as parseAggregateCommand};
