import type { EdgePgValue } from "./types";
export declare class BuiltinInputError extends Error {
    readonly code: string;
    readonly detail?: string | undefined;
    constructor(message: string, code?: string, detail?: string | undefined);
}
export type MacAddressKind = "macaddr" | "macaddr8";
export type NetworkAddressKind = "inet" | "cidr";
export declare function canonicalNetworkAddressInput(value: unknown, kind: NetworkAddressKind): string | null;
export declare function canonicalMacAddressInput(value: unknown, kind: MacAddressKind): string | null;
export declare function macAddressTrunc(value: unknown, kind: MacAddressKind): string | null;
export declare function macaddr8Set7Bit(value: unknown): string | null;
export declare function macaddr8ToMacaddr(value: unknown): string | null;
export declare function canonicalByteaInput(value: unknown): Uint8Array | null;
export declare function canonicalNumericInput(value: unknown, declaration?: string): string | null;
export declare function canonicalBooleanInput(value: EdgePgValue): boolean | null;
export declare function informationSchemaDomainBaseType(source: string): string | undefined;
export declare function canonicalCharacterInput(value: EdgePgValue, declaration: string): string | null;
export declare function canonicalInternalCharInput(value: EdgePgValue): string | null;
export type PostgresIntegerType = "smallint" | "integer" | "bigint";
export declare function canonicalIntegerInput(value: EdgePgValue, type: PostgresIntegerType): number | string | null;
export declare function canonicalOidInput(value: EdgePgValue): number | null;
export declare function canonicalPgLsnInput(value: EdgePgValue): string | null;
export declare function canonicalNameInput(value: EdgePgValue): string | null;
export declare function canonicalOidVectorInput(value: EdgePgValue): string | null;
export declare function canonicalInt2VectorInput(value: EdgePgValue): string | null;
export declare function canonicalFloatInput(value: EdgePgValue, type: "real" | "double precision"): number | string | null;
export declare function canonicalPointInput(value: EdgePgValue): string | null;
export declare function canonicalLsegInput(value: EdgePgValue): string | null;
export declare function canonicalLineInput(value: EdgePgValue): string | null;
export declare function canonicalLineFromPointInputs(left: string, right: string, errorCode?: string): string;
export declare function canonicalBoxInput(value: EdgePgValue): string | null;
export declare function canonicalPathInput(value: EdgePgValue): string | null;
export declare function canonicalPolygonInput(value: EdgePgValue): string | null;
export declare function canonicalCircleInput(value: EdgePgValue): string | null;
export declare const FLOAT_NEGATIVE_ZERO_STORAGE = "__edgepg_float_negative_zero__";
export declare function floatStorageValue(value: number | string | null): number | string | null;
export declare function exactFloat4BitsFromDecimal(source: string): number;
export declare function canonicalUuidInput(value: EdgePgValue): string | null;
export declare function canonicalMoneyInput(value: EdgePgValue): string | null;
export declare function formatMoneyOutput(value: unknown): string;
export declare function canonicalTimeInput(value: EdgePgValue, withTimezone: boolean, precision?: number): string | null;
