import{quoteIdentifier as N}from"./sql-quoting";import{EdgePgSemanticError as _}from"./semantic-error";import{ensureOperatorTypeCatalogSchema as v}from"./operator-types";import{assertSchemaPrivilege as C,canSetRole as W,ensureRoleSchema as L}from"./roles";import{prepareDropColumnsRebuild as k}from"./schema-rebuild";async function R(e){await v(e),await e.prepare(`CREATE TABLE IF NOT EXISTS __edgepg_collation_dependencies(
    collation_oid INTEGER NOT NULL,dependent_kind TEXT NOT NULL CHECK(dependent_kind IN ('column','index')),
    schema_name TEXT NOT NULL,relation_name TEXT NOT NULL,physical_name TEXT NOT NULL,
    column_name TEXT,index_name TEXT,
    PRIMARY KEY(collation_oid,dependent_kind,physical_name,column_name,index_name))`).run()}async function ce(e,n,t="edgepg",o=t,s=[t,"public"]){if(await L(e),await R(e),n.action==="create")return X(e,n,t,s);if(n.action==="drop")return Q(e,n,t,s);const r=await G(e,n.identity,s);if(await $(e,r,t),n.action==="refresh")return{command:"ALTER COLLATION",rowCount:0,notices:r.version===null?[{severity:"NOTICE",code:"00000",message:`version has not changed for collation "${E(n.identity)}"`}]:void 0};if(n.action==="rename"){if(!n.newName)throw new _("42601","new collation name is required");await j(e,{schema:r.schema_name,name:n.newName,explicitlyQualified:!0});const a=[e.prepare("UPDATE __edgepg_collations SET collation_name=?2,definition=?3,updated_at=?4 WHERE oid=?1").bind(r.oid,n.newName,n.definition,new Date().toISOString()),...await x(e,r.schema_name,r.collation_name,r.schema_name,n.newName)];await e.batch(a)}else if(n.action==="set-schema"){if(!n.newSchema)throw new _("42601","new collation schema is required");await C(e,t,n.newSchema,"CREATE"),await j(e,{schema:n.newSchema,name:r.collation_name,explicitlyQualified:!0});const a=[e.prepare("UPDATE __edgepg_collations SET schema_name=?2,definition=?3,updated_at=?4 WHERE oid=?1").bind(r.oid,n.newSchema,n.definition,new Date().toISOString()),...await x(e,r.schema_name,r.collation_name,n.newSchema,r.collation_name)];await e.batch(a)}else if(n.action==="owner"){const a=Z(n.owner,t,o);await W(e,t,a),await C(e,a,r.schema_name,"CREATE"),await e.prepare("UPDATE __edgepg_collations SET owner_name=?2,definition=?3,updated_at=?4 WHERE oid=?1").bind(r.oid,a,n.definition,new Date().toISOString()).run()}return{command:"ALTER COLLATION",rowCount:0}}async function X(e,n,t,o){const s=await K(e,n.identity,o);if(await C(e,t,s.schema,"CREATE"),await w(e,s,!1,o)){if(n.ifNotExists)return{command:"CREATE COLLATION",rowCount:0,notices:[{severity:"NOTICE",code:"42710",message:`collation "${E(s)}" already exists, skipping`}]};throw F(s)}const a=n.from?await P(e,n.from,o):q(n),i=new Date().toISOString();return await e.batch([e.prepare(`INSERT INTO __edgepg_collations
      (oid,schema_name,collation_name,owner_name,provider,deterministic,encoding,collate_locale,ctype_locale,
       locale,icu_rules,version,definition,updated_at)
      SELECT next_oid,?1,?2,?3,?4,1,?5,?6,?7,?8,NULL,?9,?10,?11
      FROM __edgepg_operator_type_oid_allocator WHERE id=1`).bind(s.schema,s.name,t,a.provider,a.encoding,a.collate,a.ctype,a.locale,a.version,n.definition,i),e.prepare("UPDATE __edgepg_operator_type_oid_allocator SET next_oid=next_oid+1 WHERE id=1")]),{command:"CREATE COLLATION",rowCount:0}}async function P(e,n,t){const o=await w(e,n,!0,t);if(!o)throw new _("42704",`collation "${E(n)}" does not exist`,404);return b(o),{provider:o.provider,encoding:o.encoding,collate:o.collate_locale,ctype:o.ctype_locale,locale:o.locale,version:o.version}}function q(e){if(e.deterministic===!1)throw g("nondeterministic collations");if(e.rules)throw g("collation rules");const n=(e.provider||"libc").toLowerCase();if(!["libc","c","builtin","b"].includes(n))throw g(`${n} collation provider`);const t=e.locale||e.lcCollate||e.lcCtype,o=e.lcCollate||t,s=e.lcCtype||t;if(!t||o!==s)throw g("different LC_COLLATE and LC_CTYPE locales");const r=t.toUpperCase().replaceAll("_","-"),a=n==="builtin"||n==="b";if(!(a?["C","C.UTF-8","C.UTF8"].includes(r):["C","POSIX"].includes(r)))throw g(`locale "${t}"`);if(e.version&&!(a&&e.version==="1"))throw g("external collation versions");return a?{provider:"b",encoding:r==="C"?-1:6,collate:null,ctype:null,locale:r==="C.UTF8"?"C.UTF-8":t,version:e.version||"1"}:{provider:"c",encoding:6,collate:t,ctype:t,locale:null,version:null}}async function Q(e,n,t,o){const s=[],r=[];for(const i of n.targets){if(i.explicitlyQualified&&!await B(e,i.schema)){if(!n.ifExists)throw new _("3F000",`schema "${i.schema}" does not exist`,404);r.push(`schema "${i.schema}" does not exist, skipping`);continue}const c=await w(e,i,!0,o);if(!c){if(n.ifExists){r.push(`collation "${E(i)}" does not exist, skipping`);continue}throw new _("42704",`collation "${E(i)}" does not exist`,404)}if(c.schema_name==="pg_catalog"&&[100,950,951].includes(c.oid))throw new _("2BP01",`cannot drop collation "${E(i)}" because it is required by the database system`);if(await $(e,c,t),await e.prepare(`SELECT dependent_kind,physical_name,column_name,index_name
      FROM __edgepg_collation_dependencies WHERE collation_oid=?1 LIMIT 1`).bind(c.oid).first()&&!n.cascade)throw new _("2BP01",`cannot drop collation "${E(i)}" because other objects depend on it`);s.push(c)}const a=[];for(const i of s)n.cascade&&a.push(...await Y(e,i.oid)),a.push(...await J(e,i.schema_name,i.collation_name)),a.push(e.prepare("DELETE FROM __edgepg_collation_dependencies WHERE collation_oid=?1").bind(i.oid),e.prepare(`DELETE FROM __edgepg_operator_type_dependencies
        WHERE refclassid=3456 AND refobjid=?1`).bind(i.oid),e.prepare("DELETE FROM __edgepg_collations WHERE oid=?1").bind(i.oid));return a.length&&await e.batch(a),{command:"DROP COLLATION",rowCount:0,...r.length?{notices:r.map(i=>({severity:"NOTICE",code:"00000",message:i}))}:{}}}async function B(e,n){return["public","pg_catalog","information_schema"].includes(n)||!!await e.prepare("SELECT 1 AS present FROM __edgepg_schemas WHERE name=?1").bind(n).first()}async function x(e,n,t,o,s){await I(e);const r=D(n,t),a=JSON.stringify(o==="public"?[s]:[o,s]);return r.map(i=>e.prepare(`UPDATE __edgepg_comments SET identity_json=?2,updated_at=?3
    WHERE object_type='OBJECT_COLLATION' AND identity_json=?1 AND argument_types_json='[]'`).bind(i,a,new Date().toISOString()))}async function J(e,n,t){return await I(e),D(n,t).map(o=>e.prepare(`DELETE FROM __edgepg_comments
    WHERE object_type='OBJECT_COLLATION' AND identity_json=?1 AND argument_types_json='[]'`).bind(o))}async function I(e){await e.prepare(`CREATE TABLE IF NOT EXISTS __edgepg_comments(
    object_type TEXT NOT NULL,identity_json TEXT NOT NULL,argument_types_json TEXT NOT NULL DEFAULT '[]',
    comment TEXT NOT NULL,updated_at TEXT NOT NULL,
    PRIMARY KEY(object_type,identity_json,argument_types_json))`).run()}function D(e,n){return[...new Set([JSON.stringify([e,n]),...e==="public"?[JSON.stringify([n])]:[]])]}async function Y(e,n){const t=(await e.prepare(`SELECT dependent_kind,schema_name,relation_name,physical_name,column_name,index_name
    FROM __edgepg_collation_dependencies WHERE collation_oid=?1 ORDER BY dependent_kind DESC`).bind(n).all()).results,o=[],s=new Set;for(const i of t.filter(c=>c.dependent_kind==="index"))s.has(i.physical_name)||(s.add(i.physical_name),o.push(e.prepare(`DROP INDEX IF EXISTS ${N(i.physical_name)}`),e.prepare("DELETE FROM __edgepg_pg_objects WHERE kind='index' AND relation_oid IS NOT NULL AND object_name=?1").bind(i.index_name)));const r=new Map;for(const i of t.filter(c=>c.dependent_kind==="column")){const c=r.get(i.physical_name)||{schema:i.schema_name,relation:i.relation_name,columns:new Set};i.column_name&&c.columns.add(i.column_name),r.set(i.physical_name,c)}const a=new Set((await e.prepare(`SELECT name FROM sqlite_master WHERE type='table' AND name IN
    ('__edgepg_unique_constraints','__edgepg_foreign_constraints','__edgepg_check_constraints')`).all()).results.map(i=>i.name));for(const[i,c]of r){const f=(await e.prepare(`PRAGMA table_info(${N(i)})`).all()).results.map(l=>l.name),p=[...c.columns].filter(l=>f.includes(l));if(!p.length)continue;if(f.length===p.length)throw g("DROP COLLATION CASCADE for last-column dependency");const u=await e.prepare(`SELECT columns_json,pg_types_json,current_columns_json,current_pg_types_json
        ,generated_columns_json FROM __edgepg_pg_tables WHERE physical_name=?1`).bind(i).first();if(!u)throw new _("XX000",`table catalog entry for ${i} does not exist`);const y=new Set(p);if(a.has("__edgepg_check_constraints")&&(await e.prepare("SELECT definition FROM __edgepg_check_constraints WHERE table_name=?1").bind(i).all()).results.some(m=>p.some(T=>new RegExp(`\\b${ee(T)}\\b`,"iu").test(m.definition))))throw g("DROP COLLATION CASCADE for CHECK constraint dependency");if(a.has("__edgepg_unique_constraints"))for(const l of p)o.push(e.prepare(`DELETE FROM __edgepg_unique_constraints WHERE table_name=?1
        AND EXISTS (SELECT 1 FROM json_each(columns_json) WHERE value=?2)`).bind(i,l));if(a.has("__edgepg_foreign_constraints"))for(const l of p)o.push(e.prepare(`DELETE FROM __edgepg_foreign_constraints WHERE table_name=?1
        AND EXISTS (SELECT 1 FROM json_each(columns_json) WHERE value=?2)`).bind(i,l));if(o.push(...await k(e,{physicalName:i,schema:c.schema,name:c.relation,columns:p,generatedColumns:V(u.generated_columns_json).filter(l=>!y.has(l.column))})),u){const l=M(u.current_columns_json||u.columns_json),m=M(u.current_pg_types_json||u.pg_types_json),T=l.map((h,S)=>({column:h,type:m[S]})).filter(({column:h})=>!y.has(h));o.push(e.prepare(`UPDATE __edgepg_pg_tables SET current_columns_json=?2,current_pg_types_json=?3
        WHERE physical_name=?1`).bind(i,JSON.stringify(T.map(h=>h.column)),JSON.stringify(T.map(h=>h.type)))),o.push(e.prepare(`DELETE FROM __edgepg_collation_dependencies
        WHERE dependent_kind='column' AND physical_name=?1 AND column_name IN (${p.map((h,S)=>`?${S+2}`).join(",")})`).bind(i,...p))}}return o}async function le(e,n,t,o=[t,"public"]){if(!n.length)return{rewrites:[],dependencies:[]};await L(e),await R(e);const s=new Map,r={rewrites:[],dependencies:[]};for(const a of n){const i=`${a.identity.schema}.${a.identity.name}:${a.identity.explicitlyQualified}`;let c=s.get(i);if(!c){if(c=await w(e,a.identity,!0,o)||void 0,!c)throw new _("42704",`collation "${E(a.identity)}" does not exist`,404);await C(e,t,c.schema_name,"USAGE"),b(c),s.set(i,c)}r.rewrites.push({start:a.start,end:a.end,replacement:"COLLATE BINARY"}),a.dependency&&r.dependencies.push({reference:a,oid:c.oid})}return r}function pe(e,n){return n.dependencies.flatMap(({reference:t,oid:o})=>{const s=t.dependency,r=e.prepare(`INSERT OR REPLACE INTO __edgepg_collation_dependencies
      (collation_oid,dependent_kind,schema_name,relation_name,physical_name,column_name,index_name)
      VALUES(?1,?2,?3,?4,?5,?6,?7)`).bind(o,s.kind,s.schema,s.relation,s.physicalName,s.column||null,s.indexName||null),a=s.kind==="column"?e.prepare(`INSERT OR REPLACE INTO __edgepg_operator_type_dependencies
          (classid,objid,objsubid,refclassid,refobjid,refobjsubid,deptype)
        SELECT 1259,table_catalog.relation_oid,CAST(column_name.key AS INTEGER)+1,3456,?1,0,'n'
        FROM __edgepg_pg_tables AS table_catalog,
          json_each(COALESCE(table_catalog.current_columns_json,table_catalog.columns_json)) AS column_name
        WHERE table_catalog.physical_name=?2 AND CAST(column_name.value AS TEXT)=?3
          AND table_catalog.relation_oid IS NOT NULL`).bind(o,s.physicalName,s.column):e.prepare(`INSERT OR REPLACE INTO __edgepg_operator_type_dependencies
          (classid,objid,objsubid,refclassid,refobjid,refobjsubid,deptype)
        SELECT 1259,relation_oid,0,3456,?1,0,'n' FROM __edgepg_pg_objects
        WHERE kind='index' AND schema_name=?2 AND object_name=?3 AND relation_oid IS NOT NULL`).bind(o,s.schema,s.indexName);return[r,a]})}function _e(e,n){const t=[],o=new Set,s=d(e)?.stmts;if(Array.isArray(s))for(const a of s){const i=d(d(a)?.stmt),c=d(i?.CreateStmt),f=U(c?.relation);if(c&&f&&Array.isArray(c.tableElts))for(const y of c.tableElts){const l=d(d(y)?.ColumnDef),m=d(l?.collClause);!l||!m||typeof l.colname!="string"||(o.add(m),t.push({identity:O(m.collname),dependency:{kind:"column",schema:f.schema,relation:f.name,physicalName:f.physical,column:l.colname}}))}const p=d(i?.IndexStmt),u=U(p?.relation);if(p&&u&&Array.isArray(p.indexParams))for(const y of p.indexParams){const l=d(d(y)?.IndexElem);if(!l||!Array.isArray(l.collation)||!l.collation.length)continue;o.add(l.collation);const m=String(p.idxname||"");t.push({identity:O(l.collation),dependency:{kind:"index",schema:u.schema,relation:u.name,physicalName:u.schema==="public"?m:`${u.schema}__${m}`,indexName:m}})}}return A(e,a=>{const i=d(a.CollateClause);i&&!o.has(i)&&(o.add(i),t.push({identity:O(i.collname)}))}),[...n.matchAll(/\bCOLLATE\s+((?:"(?:""|[^"])+"|[A-Za-z_][\w$]*)(?:\s*\.\s*(?:"(?:""|[^"])+"|[A-Za-z_][\w$]*))?)/giu)].map((a,i)=>{const c=a.index,f=c+a[0].length;return{...t[i]||{identity:ne(a[1])},start:H(n,c),end:H(n,f)}})}function b(e){if(e.provider==="d")return;const n=e.locale||e.collate_locale||"";if(!e.deterministic||!["b","c"].includes(e.provider)||!["C","POSIX","C.UTF-8","C.UTF8"].includes(n.toUpperCase().replaceAll("_","-")))throw g(`collation "${e.schema_name}.${e.collation_name}"`)}async function w(e,n,t,o=[]){if(n.explicitlyQualified||!t)return e.prepare(`SELECT * FROM __edgepg_collations
    WHERE schema_name=?1 AND collation_name=?2 ORDER BY encoding DESC LIMIT 1`).bind(n.schema,n.name).first();for(const s of z(o)){const r=await e.prepare(`SELECT * FROM __edgepg_collations
      WHERE schema_name=?1 AND collation_name=?2 ORDER BY encoding DESC LIMIT 1`).bind(s,n.name).first();if(r)return r}return null}async function G(e,n,t){const o=await w(e,n,n.explicitlyQualified===!1,t);if(!o)throw new _("42704",`collation "${E(n)}" does not exist`,404);return o}async function K(e,n,t){if(n.explicitlyQualified)return n;for(const o of t)if(await e.prepare("SELECT 1 AS present FROM __edgepg_schemas WHERE name=?1").bind(o).first())return{schema:o,name:n.name,explicitlyQualified:!1};return{schema:t[0]||"public",name:n.name,explicitlyQualified:!1}}function z(e){return[...new Set(["pg_catalog",...e.filter(n=>n!=="pg_catalog")])]}async function j(e,n){if(await e.prepare(`SELECT 1 AS present FROM __edgepg_collations
    WHERE schema_name=?1 AND collation_name=?2`).bind(n.schema,n.name).first())throw F(n)}async function $(e,n,t){if(!(await e.prepare("SELECT is_superuser FROM __edgepg_roles WHERE name=?1").bind(t).first())?.is_superuser&&n.owner_name!==t)throw new _("42501",`must be owner of collation "${n.collation_name}"`,403)}function Z(e,n,t){if(!e)throw new _("42601","new owner is required");if(e.kind==="current-role"||e.kind==="current-user")return n;if(e.kind==="session-user")return t;if(!e.name)throw new _("42601","new owner is required");return e.name}function F(e){return new _("42710",`collation "${E(e)}" already exists`,409)}function g(e){return new _("0A000",`${e} has no D1 collation provider equivalent`)}function E(e){return e.explicitlyQualified?`${e.schema}.${e.name}`:e.name}function M(e){try{const n=JSON.parse(e);return Array.isArray(n)?n.map(String):[]}catch{return[]}}function V(e){try{const n=JSON.parse(e||"[]");return Array.isArray(n)?n.filter(t=>t&&typeof t=="object"&&typeof t.column=="string"&&typeof t.expressionSql=="string"&&typeof t.stored=="boolean"):[]}catch{return[]}}function ee(e){return e.replace(/[.*+?^${}()|[\]\\]/gu,"\\$&")}function H(e,n){return new TextEncoder().encode(e.slice(0,n)).length}function O(e){const n=te(e),t=n.at(-1);if(!t)throw new _("42601","collation identity is required");return{schema:n.length>1?n.at(-2):"public",name:t,explicitlyQualified:n.length>1}}function ne(e){const n=e.split(".").map(t=>t.trim().replace(/^"|"$/gu,"").replaceAll('""','"'));return{schema:n.length>1?n.at(-2):"public",name:n.at(-1),explicitlyQualified:n.length>1}}function U(e){const n=d(e);if(!n||typeof n.relname!="string")return null;const t=typeof n.schemaname=="string"?n.schemaname:"public";return{schema:t,name:n.relname,physical:t==="public"?n.relname:`${t}__${n.relname}`}}function te(e){return Array.isArray(e)?e.flatMap(n=>typeof n=="string"?[n]:typeof d(d(n)?.String)?.sval=="string"?[String(d(d(n)?.String)?.sval)]:[]):[]}function A(e,n){if(!e||typeof e!="object")return;if(Array.isArray(e)){for(const o of e)A(o,n);return}const t=e;n(t);for(const o of Object.values(t))A(o,n)}function d(e){return e&&typeof e=="object"?e:null}export{pe as collationDependencyStatements,_e as collationReferences,R as ensureCollationSchema,ce as executeCollationCommand,le as resolveCollationReferences};
