import{quoteLiteral as y}from"./sql-quoting";import{physicalRelationNameFromParts as l}from"./relation-identity";import{EdgePgSemanticError as s}from"./semantic-error";import{catalogObjectExists as w}from"./catalog-objects";import{ensureEventTriggerSchema as S}from"./event-triggers";import{ensureOperatorTypeCatalogSchema as A}from"./operator-types";import{resolveRoutineTypeOid as O}from"./routine-types";import{roleOwnsObject as h}from"./roles";async function W(e,i,p="edgepg"){await L(e),await R(e,i,p);const n=JSON.stringify(i.identity),a=JSON.stringify(i.argumentTypes||[]),m=await M(e);return i.comment===null?await e.prepare(`DELETE FROM __edgepg_comments
      WHERE object_type=?1 AND identity_json=?2 AND argument_types_json=?3`).bind(i.objectType,n,a).run():m?await e.prepare(`INSERT INTO __edgepg_comments(object_type,object_name,sub_name,identity_json,argument_types_json,comment,updated_at)
      VALUES (?1,?2,'',?3,?4,?5,?6)
      ON CONFLICT(object_type,identity_json,argument_types_json) DO UPDATE SET
        comment=excluded.comment,updated_at=excluded.updated_at`).bind(i.objectType,n,n,a,i.comment,new Date().toISOString()).run():await e.prepare(`INSERT INTO __edgepg_comments(object_type,identity_json,argument_types_json,comment,updated_at)
      VALUES (?1,?2,?3,?4,?5)
      ON CONFLICT(object_type,identity_json,argument_types_json) DO UPDATE SET
        comment=excluded.comment,updated_at=excluded.updated_at`).bind(i.objectType,n,a,i.comment,new Date().toISOString()).run(),{command:"COMMENT",rowCount:0}}async function R(e,i,p){const n=i.identity,a=i.objectType;if(a==="OBJECT_SEQUENCE"){const t=l(n);if(!await T(e,"__edgepg_sequences",t))throw new s("42P01",`relation "${E(n)}" does not exist`,404);return}if(a==="OBJECT_MATVIEW"){const t=l(n);if(!await T(e,"__edgepg_materialized_views",t))throw new s("42P01",`materialized view "${E(n)}" does not exist`,404);return}if(["OBJECT_TABLE","OBJECT_VIEW","OBJECT_INDEX"].includes(a)){const t=a==="OBJECT_TABLE"?await d(e,n):l(n),o=a==="OBJECT_VIEW"?["view"]:a==="OBJECT_INDEX"?["index"]:["table"];if(!await e.prepare(`SELECT type FROM sqlite_master WHERE name=?1 AND type IN (${o.map((c,g)=>`?${g+2}`).join(",")})`).bind(t,...o).first())throw new s("42P01",`relation "${E(n)}" does not exist`,404);return}if(a==="OBJECT_COLUMN"){if(n.length<2)throw new s("42601","COMMENT ON COLUMN requires a relation and column");const t=n.at(-1),o=n.slice(0,-1),r=await d(e,o);if(!await e.prepare("SELECT 1 AS present FROM sqlite_master WHERE name=?1 AND type IN ('table','view')").bind(r).first())throw new s("42P01",`relation "${E(o)}" does not exist`,404);if(!(await e.prepare(`PRAGMA table_info(${y(r)})`).all()).results.some(u=>u.name===t))throw new s("42703",`column "${t}" of relation "${E(o)}" does not exist`,404);return}if(a==="OBJECT_SCHEMA"){if(!await T(e,"__edgepg_schemas",n.at(-1)))throw new s("3F000",`schema "${n.at(-1)}" does not exist`,404);return}if(a==="OBJECT_DOMAIN"||a==="OBJECT_TYPE"){const t=l(n);if(!await T(e,a==="OBJECT_DOMAIN"?"__edgepg_domains":"__edgepg_types",t))throw new s("42704",`${a==="OBJECT_DOMAIN"?"domain":"type"} ${E(n)} does not exist`,404);return}if(a==="OBJECT_AGGREGATE"){const t=l(n),o=[];for(const c of i.argumentTypes||[])o.push(await O(e,c));const r=await _(e,`SELECT routine.routine_oid FROM __edgepg_routines AS routine
      JOIN __edgepg_aggregates AS aggregate ON aggregate.aggregate_oid=routine.routine_oid
      WHERE routine.name=?1 AND routine.input_argument_type_oids_json=?2`,[t,JSON.stringify(o)]);if(!r?.routine_oid)throw new s("42883",`aggregate ${E(n)}(${(i.argumentTypes||[]).join(",")}) does not exist`,404);i.identity=[String(r.routine_oid)],i.argumentTypes=[];return}if(["OBJECT_FUNCTION","OBJECT_PROCEDURE","OBJECT_ROUTINE"].includes(a)){const t=l(n),o=JSON.stringify(i.argumentTypes||[]),r=await _(e,"SELECT routine_kind FROM __edgepg_routines WHERE name=?1 AND argument_types_json=?2",[t,o]),c=a==="OBJECT_FUNCTION"?"function":a==="OBJECT_PROCEDURE"?"procedure":void 0;if(!r||c&&r.routine_kind!==c)throw new s("42883",`${a.slice(7).toLowerCase()} ${E(n)}(${(i.argumentTypes||[]).join(",")}) does not exist`,404);return}if(a==="OBJECT_LANGUAGE"){if(!await T(e,"__edgepg_languages",n.at(-1)))throw new s("42704",`language ${n.at(-1)} does not exist`,404);return}if(a==="OBJECT_COLLATION"){const t=n.length>1?n.at(-2):"public",o=n.at(-1);if(!await _(e,`SELECT 1 AS present FROM __edgepg_collations
      WHERE schema_name=?1 AND collation_name=?2`,[t,o]))throw new s("42704",`collation "${E(n)}" does not exist`,404);return}if(a==="OBJECT_CONVERSION"){const t=n.length>1?n.at(-2):"public",o=n.at(-1);if(!await _(e,`SELECT 1 AS present FROM __edgepg_conversions
      WHERE schema_name=?1 AND conversion_name=?2`,[t,o]))throw new s("42704",`conversion "${E(n)}" does not exist`,404);return}if(a==="OBJECT_CAST"){if(n.length!==2)throw new s("42601","COMMENT ON CAST requires source and target types");const t=await O(e,n[0]),o=await O(e,n[1]);if(!await _(e,`SELECT 1 AS present FROM __edgepg_casts
      WHERE source_type_oid=?1 AND target_type_oid=?2`,[t,o]))throw new s("42704",`cast from type ${n[0]} to type ${n[1]} does not exist`,404);i.identity=[String(t),String(o)];return}if(a==="OBJECT_OPERATOR"){const t=n.length>1?n.at(-2):"public",o=n.at(-1),r=i.argumentTypes||[];if(r.length!==2)throw new s("42601","COMMENT ON OPERATOR requires two operand types");const c=await N(e,r[0]),g=await N(e,r[1]),u=await _(e,`SELECT oid FROM __edgepg_operators
      WHERE schema_name=?1 AND operator_name=?2 AND left_type_oid=?3 AND right_type_oid=?4`,[t,o,c,g]);if(!u?.oid)throw new s("42883",`operator ${E(n)}(${r.join(",")}) does not exist`,404);i.identity=[String(u.oid)],i.argumentTypes=[];return}if(a==="OBJECT_OPFAMILY"||a==="OBJECT_OPCLASS"){const t=$(n),o=await _(e,"SELECT oid FROM __edgepg_access_methods WHERE amname=?1",[t.accessMethod]);if(!o?.oid)throw new s("42704",`access method "${t.accessMethod}" does not exist`,404);const g=await _(e,`SELECT oid FROM ${a==="OBJECT_OPFAMILY"?"__edgepg_operator_families":"__edgepg_operator_classes"}
      WHERE schema_name=?1 AND ${a==="OBJECT_OPFAMILY"?"family_name":"class_name"}=?2 AND access_method_oid=?3`,[t.schema,t.name,o.oid]);if(!g?.oid)throw new s("42704",`${a==="OBJECT_OPFAMILY"?"operator family":"operator class"} ${E([t.schema,t.name])} for access method ${t.accessMethod} does not exist`,404);i.identity=[String(g.oid)],i.argumentTypes=[];return}if(a==="OBJECT_DATABASE"){const t=n.at(-1);if(!await T(e,"__edgepg_databases",t))throw new s("3D000",`database "${t}" does not exist`,404);return}if(a==="OBJECT_TABLESPACE"){const t=n.at(-1);if(!await w(e,"tablespace",t))throw new s("42704",`tablespace "${t}" does not exist`,404);return}if(a==="OBJECT_EXTENSION"){const t=n.at(-1);if(!await _(e,"SELECT 1 AS present FROM __edgepg_pg_extensions WHERE name=?1",[t]))throw new s("42704",`extension "${t}" does not exist`,404);return}if(a==="OBJECT_FDW"){const t=n.at(-1);if(!await w(e,"foreign_data_wrapper",t))throw new s("42704",`foreign-data wrapper "${t}" does not exist`,404);return}if(a==="OBJECT_FOREIGN_SERVER"){const t=n.at(-1);if(!await w(e,"foreign_server",t))throw new s("42704",`server "${t}" does not exist`,404);return}if(a==="OBJECT_USER_MAPPING"){if(n.length<2)throw new s("42601","COMMENT ON USER MAPPING requires a user and server");const t=JSON.stringify([n[0],n[1]]);if(!await w(e,"user_mapping",t))throw new s("42704",`user mapping for "${n[0]}" on server "${n[1]}" does not exist`,404);i.identity=[t];return}if(a==="OBJECT_FOREIGN_TABLE"){const t=n,o=t.length>1?t.at(-2):"public",r=t.at(-1);if(!await _(e,`SELECT 1 AS present FROM __edgepg_pg_tables
      WHERE schema_name=?1 AND table_name=?2 AND persistence='foreign'`,[o,r]))throw new s("42P01",`foreign table "${E(t)}" does not exist`,404);return}if(a==="OBJECT_STATISTIC_EXT"){const t=n.length>1?n.at(-2):"public",o=n.at(-1);if(!await _(e,`SELECT 1 AS present FROM __edgepg_statistics
      WHERE schema_name=?1 AND name=?2`,[t,o]))throw new s("42704",`statistics object "${E(n)}" does not exist`,404);return}if(a==="OBJECT_ACCESS_METHOD"){await A(e);const t=n.at(-1);if(!await _(e,"SELECT 1 AS present FROM __edgepg_access_methods WHERE amname=?1",[t]))throw new s("42704",`access method "${t}" does not exist`,404);return}if(a==="OBJECT_EVENT_TRIGGER"){await S(e);const t=n.at(-1);if(!await _(e,"SELECT 1 AS present FROM __edgepg_event_triggers WHERE name=?1",[t]))throw new s("42704",`event trigger "${t}" does not exist`,404);return}const m=J(a);if(m){const t=n.length>1?n.at(-2):"public",o=n.at(-1);if(!await _(e,`SELECT 1 AS present FROM ${m.table}
      WHERE schema_name=?1 AND ${m.nameColumn}=?2`,[t,o]))throw new s("42704",`${m.label} "${E(n)}" does not exist`,404);return}if(a==="OBJECT_POLICY"){const{relation:t,subobject:o}=f(n);if(!await _(e,"SELECT 1 AS present FROM __edgepg_policies WHERE table_name=?1 AND policy_name=?2",[await d(e,t),o]))throw new s("42704",`policy "${o}" for table "${E(t)}" does not exist`,404);return}if(a==="OBJECT_TRIGGER"){const{relation:t,subobject:o}=f(n),r=`${E(t)}.${o}`;if(!await _(e,"SELECT 1 AS present FROM __edgepg_triggers WHERE display_name=?1",[r]))throw new s("42704",`trigger "${o}" for table "${E(t)}" does not exist`,404);return}if(a==="OBJECT_TABCONSTRAINT"){const{relation:t,subobject:o}=f(n),r=await d(e,t),c=t.join(".");if(!await _(e,`SELECT 1 AS present FROM sqlite_master
      WHERE name=?1 AND type IN ('table','view')`,[r]))throw new s("42P01",`relation "${c}" does not exist`,404);if(!await _(e,`SELECT 1 AS present FROM __edgepg_check_constraints WHERE table_name=?1 AND constraint_name=?2
      UNION ALL SELECT 1 FROM __edgepg_unique_constraints WHERE table_name=?1 AND constraint_name=?2
      UNION ALL SELECT 1 FROM __edgepg_foreign_constraints WHERE table_name=?1 AND constraint_name=?2
      UNION ALL SELECT 1 FROM __edgepg_exclusion_constraints WHERE table_name=?1 AND constraint_name=?2
      UNION ALL SELECT 1 FROM __edgepg_not_null_constraints WHERE table_name=?1 AND constraint_name=?2 LIMIT 1`,[r,o]))throw new s("42704",`constraint "${o}" for table "${c}" does not exist`,404);const C=await _(e,"SELECT owner_name FROM __edgepg_table_owners WHERE physical_name=?1",[r]);if(C?.owner_name&&!await h(e,p,String(C.owner_name)))throw new s("42501",`must be owner of relation ${t.at(-1)}`,403);return}if(a==="OBJECT_DOMCONSTRAINT"){const{relation:t,subobject:o}=f(n),r=t.join("."),c=await _(e,"SELECT constraints_json,owner_name FROM __edgepg_domains WHERE name=?1",[l(t)]);if(!c)throw new s("42704",`type "${r}" does not exist`,404);if(!JSON.parse(String(c.constraints_json||"[]")).some(u=>u.name===o))throw new s("42704",`constraint "${o}" for domain ${r} does not exist`,404);if(!await h(e,p,String(c.owner_name)))throw new s("42501",`must be owner of type ${t.at(-1)}`,403);return}throw new s("0A000",`COMMENT ON ${a.replace(/^OBJECT_/,"").replaceAll("_"," ")} requires an EdgePG object adapter`)}async function L(e){await e.prepare(`CREATE TABLE IF NOT EXISTS __edgepg_comments(
    object_type TEXT NOT NULL,identity_json TEXT NOT NULL,argument_types_json TEXT NOT NULL DEFAULT '[]',
    comment TEXT NOT NULL,updated_at TEXT NOT NULL,
    PRIMARY KEY(object_type,identity_json,argument_types_json))`).run()}async function M(e){const i=await e.prepare("PRAGMA table_info('__edgepg_comments')").all(),p=new Set(i.results.map(n=>n.name));return p.has("object_name")&&p.has("sub_name")}function f(e){if(e.length<2)throw new s("42601","COMMENT target requires a relation and object name");return{relation:e.slice(0,-1),subobject:e.at(-1)}}async function d(e,i){const p=l(i),n=i.at(-1),a=i.length>1?i.at(-2):"public";try{return(await e.prepare(`SELECT physical_name FROM __edgepg_pg_tables
      WHERE schema_name=?1 AND table_name=?2`).bind(a,n).first())?.physical_name||p}catch(m){if(/no such table:\s*__edgepg_pg_tables/iu.test(m instanceof Error?m.message:String(m)))return p;throw m}}function E(e){return e.length===1?`public.${e[0]}`:e.slice(-2).join(".")}async function N(e,i){return/^none$/iu.test(i)?0:O(e,i)}function $(e){if(e.length>=3)return{accessMethod:e[0],schema:e.at(-2),name:e.at(-1)};if(e.length===2)return{accessMethod:e[0],schema:"public",name:e[1]};throw new s("42601","COMMENT ON operator family/class requires an access method and object name")}function J(e){return{OBJECT_TSPARSER:{table:"__edgepg_ts_parsers",nameColumn:"parser_name",label:"text search parser"},OBJECT_TSTEMPLATE:{table:"__edgepg_ts_templates",nameColumn:"template_name",label:"text search template"},OBJECT_TSDICTIONARY:{table:"__edgepg_ts_dictionaries",nameColumn:"dictionary_name",label:"text search dictionary"},OBJECT_TSCONFIGURATION:{table:"__edgepg_ts_configurations",nameColumn:"configuration_name",label:"text search configuration"}}[e]}async function T(e,i,p){return!!await _(e,`SELECT 1 AS present FROM ${i} WHERE name=?1`,[p])}async function _(e,i,p){try{return await e.prepare(i).bind(...p).first()}catch(n){if(/no such table/i.test(n instanceof Error?n.message:String(n)))return null;throw n}}export{L as ensureCommentSchema,W as executeCommentCommand};
