import{quoteIdentifier as E}from"./sql-quoting";import{EdgePgSemanticError as r}from"./semantic-error";import{dropTriggerDependencyStatements as d}from"./triggers";async function O(e,n){await p(e);const t=n.name.toLowerCase();if(n.action==="create"){if(n.handler&&!n.baseLanguage)throw new r("42883",`function ${n.handler}() does not exist`);if(await e.prepare("SELECT 1 AS present FROM __edgepg_languages WHERE name=?1").bind(t).first()&&!n.replace)throw new r("42710",`language ${n.name} already exists`,409);return await e.prepare(`INSERT INTO __edgepg_languages(name,base_language,trusted,definition,updated_at)
      VALUES (?1,?2,?3,?4,?5) ON CONFLICT(name) DO UPDATE SET
      base_language=excluded.base_language,trusted=excluded.trusted,definition=excluded.definition,updated_at=excluded.updated_at`).bind(t,n.baseLanguage||"sql",n.trusted?1:0,n.definition,new Date().toISOString()).run(),{command:"CREATE LANGUAGE",rowCount:0}}if(!await e.prepare("SELECT base_language FROM __edgepg_languages WHERE name=?1").bind(t).first()){if(n.action==="drop"&&n.ifExists)return{command:"DROP LANGUAGE",rowCount:0,notices:[{severity:"NOTICE",code:"00000",message:`language "${n.name}" does not exist, skipping`}]};throw new r("42704",`language "${n.name}" does not exist`,404)}if(t==="sql"||t==="plpgsql")throw new r("2BP01",`cannot ${n.action} required language ${n.name}`);if(n.action==="rename"){const a=n.newName?.toLowerCase();if(!a)throw new r("42601","ALTER LANGUAGE RENAME requires a new name");if(await e.prepare("SELECT 1 AS present FROM __edgepg_languages WHERE name=?1").bind(a).first())throw new r("42710",`language ${n.newName} already exists`,409);const u=[e.prepare("UPDATE __edgepg_languages SET name=?2,definition=?3,updated_at=?4 WHERE name=?1").bind(t,a,A(n.definition,a),new Date().toISOString()),...await f(e,t,a)],T=await l(e,t);for(const g of T)u.push(e.prepare(`UPDATE __edgepg_routines SET
      declared_language=?3,definition=?4,updated_at=?5 WHERE name=?1 AND argument_types_json=?2`).bind(g.name,g.argument_types_json,a,R(g.definition,t,a),new Date().toISOString()));return await e.batch(u),{command:"ALTER LANGUAGE",rowCount:0}}const o=await l(e,t);if(o.length&&!n.cascade)throw new r("2BP01",`cannot drop language ${n.name} because routines depend on it`);const s=[];for(const a of o)a.routine_kind==="function"&&a.argument_types_json==="[]"&&s.push(...await d(e,a.name,!0)),s.push(e.prepare("DELETE FROM __edgepg_routines WHERE name=?1 AND argument_types_json=?2").bind(a.name,a.argument_types_json));return s.push(e.prepare("DELETE FROM __edgepg_languages WHERE name=?1").bind(t)),s.push(...await w(e,t)),await e.batch(s),{command:"DROP LANGUAGE",rowCount:0}}async function f(e,n,t){return await _(e,"__edgepg_comments")?[e.prepare(`UPDATE __edgepg_comments SET identity_json=?2,updated_at=?3
    WHERE object_type='OBJECT_LANGUAGE' AND identity_json=?1`).bind(JSON.stringify([n]),JSON.stringify([t]),new Date().toISOString())]:[]}async function w(e,n){return await _(e,"__edgepg_comments")?[e.prepare(`DELETE FROM __edgepg_comments
    WHERE object_type='OBJECT_LANGUAGE' AND identity_json=?1`).bind(JSON.stringify([n]))]:[]}async function m(e,n){await p(e);const t=n.toLowerCase(),i=await e.prepare("SELECT base_language FROM __edgepg_languages WHERE name=?1").bind(t).first();if(!i)throw new r("42704",`language ${n} does not exist`,404);return i.base_language}async function p(e){await e.batch([e.prepare(`CREATE TABLE IF NOT EXISTS __edgepg_languages(
      name TEXT PRIMARY KEY,base_language TEXT NOT NULL CHECK(base_language IN ('sql','plpgsql')),
      trusted INTEGER NOT NULL,definition TEXT NOT NULL,updated_at TEXT NOT NULL)`),e.prepare(`INSERT OR IGNORE INTO __edgepg_languages VALUES
      ('sql','sql',1,'CREATE LANGUAGE sql',CURRENT_TIMESTAMP)`),e.prepare(`INSERT OR IGNORE INTO __edgepg_languages VALUES
      ('plpgsql','plpgsql',1,'CREATE LANGUAGE plpgsql',CURRENT_TIMESTAMP)`)])}async function _(e,n){return!!await e.prepare("SELECT 1 AS present FROM sqlite_master WHERE type='table' AND name=?1").bind(n).first()}async function l(e,n){try{return(await e.prepare(`SELECT name,argument_types_json,routine_kind,definition FROM __edgepg_routines
      WHERE declared_language=?1`).bind(n).all()).results}catch(t){if(/no such table|no such column/i.test(t instanceof Error?t.message:String(t)))return[];throw t}}function A(e,n){return e.replace(/^(\s*ALTER\s+LANGUAGE\s+)(?:"(?:""|[^"])+"|[\w$]+)/i,`$1${E(n)}`)}function R(e,n,t){const i=new RegExp(`(\\bLANGUAGE\\s+)(?:"${c(n)}"|${c(n)})(?![A-Za-z0-9_$])`,"i");return e.replace(i,`$1${E(t)}`)}function c(e){return e.replace(/[.*+?^${}()|[\]\\]/g,"\\$&")}export{p as ensureLanguageSchema,O as executeLanguageCommand,m as resolveRoutineLanguage};
