import { EdgePgRuntime } from "./runtime-core";
import type { EdgePgConfig, EdgePgDiagnosticsEvent, EdgePgDiagnosticsSink, EdgePgNotification, EdgePgValue, FieldDef, QueryInput, QueryResult } from "./types";
type QueryCallback<T extends Record<string, unknown>> = (error: Error | null, result?: QueryResult<T>) => void;
type ConnectionCallback = (error?: Error) => void;
type PoolConnectCallback = (error: Error | null, client?: Client, release?: () => void) => void;
type EventListener = (...args: unknown[]) => void;
type TypeParser = (value: string) => unknown;
type PoolConfig = EdgePgConfig & {
    max?: number;
};
export declare const builtins: {
    readonly BOOL: 16;
    readonly BYTEA: 17;
    readonly CHAR: 18;
    readonly INT8: 20;
    readonly INT2: 21;
    readonly INT4: 23;
    readonly REGPROC: 24;
    readonly TEXT: 25;
    readonly OID: 26;
    readonly TID: 27;
    readonly XID: 28;
    readonly CID: 29;
    readonly JSON: 114;
    readonly XML: 142;
    readonly PG_NODE_TREE: 194;
    readonly SMGR: 210;
    readonly PATH: 602;
    readonly POLYGON: 604;
    readonly CIDR: 650;
    readonly FLOAT4: 700;
    readonly FLOAT8: 701;
    readonly ABSTIME: 702;
    readonly RELTIME: 703;
    readonly TINTERVAL: 704;
    readonly CIRCLE: 718;
    readonly MACADDR8: 774;
    readonly MONEY: 790;
    readonly MACADDR: 829;
    readonly INET: 869;
    readonly ACLITEM: 1033;
    readonly BPCHAR: 1042;
    readonly VARCHAR: 1043;
    readonly DATE: 1082;
    readonly TIME: 1083;
    readonly TIMESTAMP: 1114;
    readonly TIMESTAMPTZ: 1184;
    readonly INTERVAL: 1186;
    readonly TIMETZ: 1266;
    readonly BIT: 1560;
    readonly VARBIT: 1562;
    readonly NUMERIC: 1700;
    readonly REFCURSOR: 1790;
    readonly REGPROCEDURE: 2202;
    readonly REGOPER: 2203;
    readonly REGOPERATOR: 2204;
    readonly REGCLASS: 2205;
    readonly REGTYPE: 2206;
    readonly UUID: 2950;
    readonly TXID_SNAPSHOT: 2970;
    readonly PG_LSN: 3220;
    readonly PG_NDISTINCT: 3361;
    readonly PG_DEPENDENCIES: 3402;
    readonly TSVECTOR: 3614;
    readonly TSQUERY: 3615;
    readonly GTSVECTOR: 3642;
    readonly REGCONFIG: 3734;
    readonly REGDICTIONARY: 3769;
    readonly JSONB: 3802;
    readonly REGNAMESPACE: 4089;
    readonly REGROLE: 4096;
};
export declare const types: {
    builtins: {
        readonly BOOL: 16;
        readonly BYTEA: 17;
        readonly CHAR: 18;
        readonly INT8: 20;
        readonly INT2: 21;
        readonly INT4: 23;
        readonly REGPROC: 24;
        readonly TEXT: 25;
        readonly OID: 26;
        readonly TID: 27;
        readonly XID: 28;
        readonly CID: 29;
        readonly JSON: 114;
        readonly XML: 142;
        readonly PG_NODE_TREE: 194;
        readonly SMGR: 210;
        readonly PATH: 602;
        readonly POLYGON: 604;
        readonly CIDR: 650;
        readonly FLOAT4: 700;
        readonly FLOAT8: 701;
        readonly ABSTIME: 702;
        readonly RELTIME: 703;
        readonly TINTERVAL: 704;
        readonly CIRCLE: 718;
        readonly MACADDR8: 774;
        readonly MONEY: 790;
        readonly MACADDR: 829;
        readonly INET: 869;
        readonly ACLITEM: 1033;
        readonly BPCHAR: 1042;
        readonly VARCHAR: 1043;
        readonly DATE: 1082;
        readonly TIME: 1083;
        readonly TIMESTAMP: 1114;
        readonly TIMESTAMPTZ: 1184;
        readonly INTERVAL: 1186;
        readonly TIMETZ: 1266;
        readonly BIT: 1560;
        readonly VARBIT: 1562;
        readonly NUMERIC: 1700;
        readonly REFCURSOR: 1790;
        readonly REGPROCEDURE: 2202;
        readonly REGOPER: 2203;
        readonly REGOPERATOR: 2204;
        readonly REGCLASS: 2205;
        readonly REGTYPE: 2206;
        readonly UUID: 2950;
        readonly TXID_SNAPSHOT: 2970;
        readonly PG_LSN: 3220;
        readonly PG_NDISTINCT: 3361;
        readonly PG_DEPENDENCIES: 3402;
        readonly TSVECTOR: 3614;
        readonly TSQUERY: 3615;
        readonly GTSVECTOR: 3642;
        readonly REGCONFIG: 3734;
        readonly REGDICTIONARY: 3769;
        readonly JSONB: 3802;
        readonly REGNAMESPACE: 4089;
        readonly REGROLE: 4096;
    };
    getTypeParser(oid: number, format?: string): TypeParser;
    setTypeParser(oid: number, format: string | TypeParser, parser?: TypeParser): void;
    arrayParser: {
        create(source: string, transform?: TypeParser): {
            parse: () => unknown[];
        };
    };
};
export declare class TypeOverrides {
    private readonly parsers;
    getTypeParser(oid: number, format?: string): TypeParser;
    setTypeParser(oid: number, format: string | TypeParser, parser?: TypeParser): void;
}
export declare class DatabaseError extends Error {
    severity: string;
    code?: string;
    detail?: string;
    hint?: string;
    schema?: string;
    table?: string;
    column?: string;
    constraint?: string;
    constructor(message: string, _length?: number, name?: string);
}
export declare class PgEventEmitter {
    private readonly listeners;
    on(event: string, listener: EventListener): this;
    once(event: string, listener: EventListener): this;
    removeListener(event: string, listener: EventListener): this;
    off(event: string, listener: EventListener): this;
    emit(event: string, ...args: unknown[]): boolean;
    protected listenerCount(event: string): number;
}
export declare class Client extends PgEventEmitter {
    readonly runtime: EdgePgRuntime;
    readonly connection: PgEventEmitter;
    private connected;
    private connecting?;
    constructor(config?: EdgePgConfig);
    connect(callback?: ConnectionCallback): Promise<void>;
    query<T extends Record<string, unknown> = Record<string, unknown>>(input: QueryInput<T>, values?: EdgePgValue[] | QueryCallback<T>, callback?: QueryCallback<T>): Promise<QueryResult<T>>;
    describe(sql: string): Promise<FieldDef[]>;
    copyRows(relationSql: string, columns: string[], rows: EdgePgValue[][]): Promise<number>;
    markTransactionFailed(code: string, message: string): Promise<void>;
    end(callback?: ConnectionCallback): Promise<void>;
    get readyForQuery(): boolean;
    get bookmark(): string | undefined;
    get notificationSessionId(): string;
    pollNotifications(): Promise<EdgePgNotification[]>;
    get authorization(): {
        authenticatedUser: string;
        sessionUser: string;
        currentRole: string;
    };
    sessionSetting(name: string): string;
}
export declare class Pool extends PgEventEmitter {
    readonly options: PoolConfig;
    private readonly idle;
    private readonly clients;
    private readonly waiters;
    private readonly max;
    private ended;
    constructor(config?: PoolConfig);
    query<T extends Record<string, unknown> = Record<string, unknown>>(input: QueryInput<T>, values?: EdgePgValue[]): Promise<QueryResult<T>>;
    connect(callback?: PoolConnectCallback): Promise<Client & {
        release(): void;
    }>;
    end(callback?: ConnectionCallback): Promise<void>;
    private acquire;
    private release;
}
export { EdgePgCompatibilityError, EdgePgWriteFenceError } from "./planner";
export type { EdgePgConfig, EdgePgDiagnosticsEvent, EdgePgDiagnosticsSink, FieldDef, QueryConfig, QueryResult } from "./types";
export interface DiagnosticsCollector {
    readonly sink: EdgePgDiagnosticsSink;
    events(): EdgePgDiagnosticsEvent[];
    reset(): void;
    summary(): DiagnosticsSummary;
}
export interface DiagnosticsSummary {
    eventCount: number;
    routes: {
        total: number;
        primary: number;
        replica: number;
        direct: number;
        firstPrimary: number;
        firstUnconstrained: number;
        bookmark: number;
    };
    d1: {
        operations: number;
        statements: number;
        rows: number;
        durationMs: number;
        errors: number;
        meta: Record<string, number>;
    };
    durableObjects: {
        gets: number;
        fetches: number;
        durationMs: number;
        errors: number;
    };
}
export declare function createDiagnosticsCollector(options?: {
    maxEvents?: number;
}): DiagnosticsCollector;
declare const _default: {
    Client: typeof Client;
    createDiagnosticsCollector: typeof createDiagnosticsCollector;
    DatabaseError: typeof DatabaseError;
    Pool: typeof Pool;
    TypeOverrides: typeof TypeOverrides;
    types: {
        builtins: {
            readonly BOOL: 16;
            readonly BYTEA: 17;
            readonly CHAR: 18;
            readonly INT8: 20;
            readonly INT2: 21;
            readonly INT4: 23;
            readonly REGPROC: 24;
            readonly TEXT: 25;
            readonly OID: 26;
            readonly TID: 27;
            readonly XID: 28;
            readonly CID: 29;
            readonly JSON: 114;
            readonly XML: 142;
            readonly PG_NODE_TREE: 194;
            readonly SMGR: 210;
            readonly PATH: 602;
            readonly POLYGON: 604;
            readonly CIDR: 650;
            readonly FLOAT4: 700;
            readonly FLOAT8: 701;
            readonly ABSTIME: 702;
            readonly RELTIME: 703;
            readonly TINTERVAL: 704;
            readonly CIRCLE: 718;
            readonly MACADDR8: 774;
            readonly MONEY: 790;
            readonly MACADDR: 829;
            readonly INET: 869;
            readonly ACLITEM: 1033;
            readonly BPCHAR: 1042;
            readonly VARCHAR: 1043;
            readonly DATE: 1082;
            readonly TIME: 1083;
            readonly TIMESTAMP: 1114;
            readonly TIMESTAMPTZ: 1184;
            readonly INTERVAL: 1186;
            readonly TIMETZ: 1266;
            readonly BIT: 1560;
            readonly VARBIT: 1562;
            readonly NUMERIC: 1700;
            readonly REFCURSOR: 1790;
            readonly REGPROCEDURE: 2202;
            readonly REGOPER: 2203;
            readonly REGOPERATOR: 2204;
            readonly REGCLASS: 2205;
            readonly REGTYPE: 2206;
            readonly UUID: 2950;
            readonly TXID_SNAPSHOT: 2970;
            readonly PG_LSN: 3220;
            readonly PG_NDISTINCT: 3361;
            readonly PG_DEPENDENCIES: 3402;
            readonly TSVECTOR: 3614;
            readonly TSQUERY: 3615;
            readonly GTSVECTOR: 3642;
            readonly REGCONFIG: 3734;
            readonly REGDICTIONARY: 3769;
            readonly JSONB: 3802;
            readonly REGNAMESPACE: 4089;
            readonly REGROLE: 4096;
        };
        getTypeParser(oid: number, format?: string): TypeParser;
        setTypeParser(oid: number, format: string | TypeParser, parser?: TypeParser): void;
        arrayParser: {
            create(source: string, transform?: TypeParser): {
                parse: () => unknown[];
            };
        };
    };
};
export default _default;
