import type { EdgePgConfig, EdgePgValue, EdgePgNotification, FieldDef, QueryResult } from "./types";
export declare class EdgePgRuntime {
    private bindings?;
    private readonly implicitBindings;
    private readonly databaseBinding;
    private readonly coordinatorBinding;
    private readonly planner?;
    private readonly plugins;
    private readonly writeFenceBinding;
    private readonly authenticatedUser;
    private readonly databaseName;
    private readonly databaseOwner;
    private readonly authentication;
    private readonly passwordProvider;
    private readonly admissionRequired;
    private admission?;
    private connecting?;
    private sessionUser;
    private currentRole;
    private readonly startupSettings;
    private readonly connectionSettings;
    private readonly settings;
    private readonly pendingStartupSettingOverrides;
    private settingsSnapshot?;
    private roleSettingsLoaded;
    private lastRoleSessionRefreshAt;
    private readonly cursors;
    private transactionOriginalCursorNames;
    private cursorSavepoints;
    private readonly preparedStatements;
    private preparedExecutionDepth;
    private inheritedMutationFanoutDepth;
    private mutationReturningSourceWildcardDepth;
    private readonly planCache;
    private readonly tablePrivilegeCache;
    private readonly ownedTablePrivilegeCache;
    private readonly inactiveRowSecurityCache;
    private readonly transactionRowSecurityTablesTouched;
    private readonly triggerProgramPresenceCache;
    private readonly ruleProgramPresenceCache;
    private readonly customTypeColumnPresenceCache;
    private readonly customTypeColumnNameCache;
    private readonly mutationClosureCache;
    private readonly foreignTableCache;
    private viewOwnerSourceCatalogPresent;
    private ruleCatalogPresent;
    private readonly loadedLibraries;
    private preparedPlanGeneration;
    private readonly readReplication;
    private readonly advancedManifestDefined;
    private readonly advancedTables;
    private bookmarkValue?;
    private activeSession?;
    private transactionId?;
    private transactionTimestampValue?;
    private readonly transactionWorkspaceId;
    private transactionWorkspaceStub?;
    private transactionLockStub?;
    private transactionLockHeld;
    private transactionLockExpiresAt;
    private readonly optimisticConflictLocks;
    private readonly advisoryTransactionLocks;
    private optimisticAppendTransaction;
    private transactionStatementSeen;
    private transactionModeStatementSeen;
    private transactionFailed;
    private transactionWorkspaceStarted;
    private transactionRelationCatalogChanged;
    private transactionTypeWorkspaceStarted;
    private copyRowsTarget?;
    private directOptimisticTransaction?;
    private readonly directOptimisticTableBlockCache;
    private readonly directOptimisticForeignKeyCache;
    private readonly directOptimisticReferencedForeignKeyCache;
    private readonly directOptimisticUniqueKeyCache;
    private readonly directOptimisticArrayColumnCache;
    private readonly postgresTableDefaultCache;
    private readonly extensionCastRelationPgTypeCache;
    private readonly ordinaryTypeOidInstanceCache;
    private readonly commitSchemaCache;
    private transactionOriginalSettings?;
    private transactionCommitSettings?;
    private transactionSettingSavepoints;
    private readonly sequenceState;
    private readonly temporaryRelations;
    private temporaryRelationSequence;
    private readonly notificationSessionIdValue;
    private readonly preserveNotificationSessionOnClose;
    private readonly notificationProcessId;
    private notificationActive;
    private readonly listeningChannels;
    private notificationOperations;
    private notificationSavepoints;
    private roleSchemaReady;
    private tableOwnershipSchemaReady;
    private eventTriggerCatalogPresent?;
    private readonly schemaPrivilegeCache;
    private readonly diagnostics?;
    private readonly plpgsqlParser;
    constructor(config?: EdgePgConfig);
    connect(): Promise<void>;
    private openConnection;
    private installPostgresCatalog;
    private installPostgresCatalogStorage;
    private installPostgresTableIntrospectionStorage;
    private installPostgresObjectCatalogStorage;
    private ensureMaterializedViewIntrospectionSchema;
    private ensurePostgresCatalogForRelations;
    private assertCachedTablePrivileges;
    private cacheOwnedTablePrivileges;
    private rememberOwnedTablePrivileges;
    private rememberCreatedTableTypeOids;
    private rememberCreatedTableForeignAccess;
    private rememberCreatedTableColdMetadata;
    private rememberCreatedTableVersionTriggerAbsence;
    private forgetRuleProgramPresence;
    private setOperationAllQuery;
    query<T extends Record<string, unknown> = Record<string, unknown>>(sql: string, values?: EdgePgValue[], rowMode?: "array", schemaFenceDeadline?: number): Promise<QueryResult<T>>;
    copyRows(relationSql: string, columns: string[], rows: EdgePgValue[][]): Promise<number>;
    markTransactionFailed(code: string, message: string): Promise<void>;
    describe(sql: string): Promise<FieldDef[]>;
    private dataModifyingCteQuery;
    private procedureCall;
    private anonymousBlock;
    private tableLock;
    private advisoryXactLock;
    private advisoryTransactionKey;
    private acquireAdvisoryTransactionLock;
    private assertLockTargetExists;
    private allocateImplicitIndexName;
    private assertGroupingSemantics;
    private attachGroupingConstraintDependencies;
    private scopeTemporaryRelations;
    private scopeSearchPathRelations;
    private temporaryRelationForReference;
    private forgetDroppedTemporaryRelations;
    private forgetTemporaryRelationByPhysicalName;
    private discardTemporaryRelations;
    private applyTemporaryOnCommit;
    private temporaryOnCommitForeignKeyError;
    private finishTemporaryTransaction;
    get bookmark(): string | undefined;
    get notificationSessionId(): string;
    get authorization(): {
        authenticatedUser: string;
        sessionUser: string;
        currentRole: string;
    };
    sessionSetting(name: string): string;
    close(): Promise<void>;
    pollNotifications(): Promise<EdgePgNotification[]>;
    private eventCommand;
    private transactionCommand;
    private startTransaction;
    private currentTransactionMode;
    private staticTransactionCommand;
    private transactionModeCommand;
    private cursorCommand;
    private preparedCommand;
    private preparedTypeIdentities;
    private inferPreparedParameterTypes;
    private preparedResultTypes;
    private preparedFailure;
    private assertUpdateWholeRowAssignmentTypes;
    private updateWholeRowAssignmentFailure;
    private applyDefaultTransactionMode;
    private transactionModeChanges;
    private readOnlyMutationBlocked;
    private applyTransactionMode;
    private failTransaction;
    private sessionCommand;
    private discardCommand;
    private sessionSettingTargets;
    private syncAuthorizationFromSettings;
    private initializeRoleSettings;
    private refreshRoleAdmission;
    private reloadStartupSettings;
    private loadStartupSettings;
    private applySessionSetting;
    private rememberPendingStartupSetting;
    private beginTransactionSettings;
    private beginTransactionCursors;
    private finishTransactionCursors;
    private saveCursorSavepoint;
    private rollbackCursorSavepoint;
    private releaseCursorSavepoint;
    private cursorSavepointIndex;
    private beginNotificationTransaction;
    private finishNotificationTransaction;
    private applyListeningChannelOperations;
    private saveNotificationSavepoint;
    private rollbackNotificationSavepoint;
    private releaseNotificationSavepoint;
    private notificationSavepointIndex;
    private finishTransactionSettings;
    private saveTransactionSettings;
    private rollbackTransactionSettings;
    private releaseTransactionSettings;
    private transactionSettingSavepointIndex;
    private replaceSettings;
    private setSessionSetting;
    private deleteSessionSetting;
    private settingsRecord;
    private invalidateSettingsSnapshot;
    private autocommitRowLockQuery;
    private transactionQuery;
    private mergeCommand;
    private transactionRequest;
    private inheritedMutationQuery;
    private ensureCachedRoleSchema;
    private ensureCachedTableOwnershipSchema;
    private assertCachedCreateTableSchemaPrivilege;
    private assertCachedSchemaPrivilege;
    private assertCachedTransactionPrivileges;
    private assertCachedViewOwnerSourcePrivileges;
    private ordinaryTransactionDmlQuery;
    private directOptimisticDmlQuery;
    private directOptimisticAdvancedTableAllowed;
    private loadDirectOptimisticAdvancedTableAllowed;
    private directOptimisticArrayColumns;
    private directOptimisticArrayValuesCompatible;
    private directOptimisticDmlBlocked;
    private directOptimisticBuiltinTypeWriteRewrites;
    private directOptimisticPendingUpdateBlocked;
    private directOptimisticTableBlocked;
    private loadDirectOptimisticTableBlocked;
    private directOptimisticTableBlockedFromCatalogs;
    private rememberDirectOptimisticInsertConstraintCatalogs;
    private directOptimisticDeleteBlocked;
    private directOptimisticParentDeleteSafe;
    private directOptimisticUpdateColumnsBlocked;
    private loadDirectOptimisticUpdateColumnsBlocked;
    private directOptimisticInsertForeignConstraints;
    private loadDirectOptimisticInsertForeignConstraints;
    private directOptimisticReferencedForeignConstraints;
    private loadDirectOptimisticReferencedForeignConstraints;
    private forgetDirectOptimisticTableBlocks;
    private forgetPostgresTableDefaultMetadata;
    private ensureDirectOptimisticTransaction;
    private applyDirectOptimisticDml;
    private applyDirectOptimisticUpsert;
    private directOptimisticInsertValues;
    private assertInsertDoesNotOmitRequiredPrimaryKey;
    private directOptimisticInsertValuesWithMetadata;
    private directOptimisticPhysicalDefaultMetadataInsertValues;
    private directOptimisticPhysicalDefaultInsertValues;
    private directOptimisticPhysicalDefaultSchemaInsertValues;
    private hydrateDirectOptimisticPendingRow;
    private applyDirectOptimisticInsertRows;
    private applyDirectOptimisticUpdateKeys;
    private applyDirectOptimisticDeleteKeys;
    private directOptimisticInsertUniqueConstraints;
    private loadDirectOptimisticInsertUniqueConstraints;
    private directOptimisticUniqueViolation;
    private directOptimisticPrimaryKeyViolation;
    private directOptimisticPrimaryConstraintName;
    private directOptimisticForeignKeyViolation;
    private directOptimisticCheckViolation;
    private validateDirectOptimisticChecks;
    private validateDirectOptimisticInsertUniqueKeys;
    private validateDirectOptimisticInsertForeignKeys;
    private validateDirectOptimisticInsertPrimaryAndForeignKeys;
    private validateDirectOptimisticInsertRowsForeignKeys;
    private directOptimisticInsertConstraintValues;
    private directOptimisticSelectQuery;
    private directOptimisticRowSelectRows;
    private flushDirectOptimisticTransaction;
    private prepareTransactionTriggers;
    private prepareRuleExecution;
    private hasTriggerPrograms;
    private hasCustomTypeColumns;
    private customTypeWritesTouchCustomColumns;
    private builtinJsonbOperatorsRequireRewrite;
    private builtinTemporalOperatorsRequireRewrite;
    private customTypeOperatorsTouchCustomColumns;
    private customTypeColumnNames;
    private committedMutationTables;
    private assertCachedNoForeignTableAccess;
    private rememberForeignTableAccess;
    private rememberMutationClosure;
    private forgetMutationClosures;
    private transactionWorkspace;
    private beginTransactionRuntimeState;
    private noteStaticTransactionQuery;
    private notificationRequest;
    private preparedTransactionRequest;
    private coordinateTransactionStatement;
    private canUseLockFreeSchemaDdl;
    private shouldDispatchDdlEventTriggers;
    private coordinatorNamespace;
    private acquireTransactionLock;
    private acquireOptimisticConflictLocks;
    private acquireSelectForUpdateLock;
    private acquireParsedOptimisticConflictLocks;
    private renewOptimisticConflictLocks;
    private renewAdvisoryTransactionLocks;
    private renewTransactionLock;
    private withTransactionLockHeartbeat;
    private releaseTransactionLock;
    private explicitTransactionLock;
    private databaseCoordinatorObjectName;
    private optimisticConflictCoordinatorObjectName;
    private advisoryTransactionCoordinatorObjectName;
    private notificationCoordinatorObjectName;
    private plan;
    private resolveDatabase;
    private refreshRequestBindings;
    private roleSettingsDatabase;
    private requiresPrimary;
    private resolveOrdinaryFastPath;
    private builtinTypeWritesRequireRewrite;
    private builtinTypeComparisonsRequireRewrite;
    private builtinMoneyOperatorsRequireRewrite;
    private builtinPointOperatorsRequireRewrite;
    private builtinMacAddressOperatorsRequireRewrite;
    private builtinIntegerOperatorsRequireRewrite;
    private builtinFloatOperatorsRequireRewrite;
    private hasActiveRowSecurityFastPathBlocker;
    private ordinaryFastPath;
    private ordinaryCompatiblePlan;
    private ordinaryTransactionDmlCompatiblePlan;
    private ensureCreatedTableVisible;
    private createdTableVisibilityProbe;
    private finishCreatedTableVisibility;
    private createdTableInsertBlocked;
    private rememberCreatedTableInsertFastPath;
    private rememberDirectOptimisticTableBlockFastPath;
    private rememberCreatedTableVisibilityMetadata;
    private sessionExpressionRewrites;
    private assertUnicodeStringSafety;
    private legacyStringLiteralSql;
    private assertPreparseUnicodeStringSafety;
    private inputValidationRewrites;
    private regObjectFunctionRewrites;
    private staticSessionSelect;
    private currentSchemasSelect;
    private staticCatalogSelect;
    private informationSchemaColumnsSimpleSelect;
    private typeormColumnsMetadataSelect;
    private typeormConstraintsMetadataSelect;
    private sequelizeIndexMetadataSelect;
    private pgDumpIndexMetadataSelect;
    private psqlDescribeRelationSelect;
    private psqlDescribeTypesSelect;
    private psqlRelationLookupSelect;
    private psqlDescribeAttributesSelect;
    private psqlDescribeIndexesSelect;
    private psqlDescribeChecksSelect;
    private psqlDescribeRulesSelect;
    private psqlDescribeForeignKeysSelect;
    private psqlDescribeNotNullSelect;
    private psqlDescribePoliciesSelect;
    private psqlDescribeStatisticsSelect;
    private psqlDescribePublicationsSelect;
    private psqlDescribeInheritanceSelect;
    private pgDumpAttributeDefaultMetadataSelect;
    private sequelizeDynamicOidSelect;
    private slonikTypeParserBootstrapSelect;
    private typeormForeignKeyMetadataSelect;
    private schemaIntrospectionRelationRewrites;
    private schemaPrivilegeFunctionRewrites;
    private activeRowSecurityReferences;
    private viewDefinitionFunctionRewrites;
    private cachedBigintSequenceColumns;
    private cacheSequenceColumns;
    private rememberCreatedTableSequenceDefaultColumns;
    private rememberCreatedTableCustomTypeColumns;
    private rememberCreatedTableDefaultMetadata;
    private rememberCreatedTablePrimaryKeyColumn;
    private rememberCreatedTableDirectOptimisticConstraints;
    private rememberCreatedTableDirectOptimisticMutationFastPaths;
    private showSetting;
}
export declare function formatPostgresNumeric(source: string, rawFormat: string, sourceOid?: number): string;
export declare function parsePostgresNumber(rawInput: string, rawFormat: string): string;
export declare function singleRowVersionTriggerMutation(sql: string, command: string, keyColumn?: string): boolean;
export declare function singleRowVersionTriggerMutationShape(sql: string, command: string): boolean;
export declare function versionTriggerMutationRequiresPrimaryOnlyTable(sql: string, command: string): boolean;
export declare function versionTriggerPrimaryKeyOnlyTable(database: D1Database, table: string, keyColumn: string): Promise<boolean>;
export declare function prepareRuleExecution(db: D1Database, table: string, event: "insert" | "update" | "delete", options?: {
    catalogPresent?: boolean;
}): Promise<{
    skipPrimary: boolean;
    beforeStatements: D1PreparedStatement[];
    afterStatements: D1PreparedStatement[];
    tables: string[];
    catalogPresent: false;
    viewRewrite: undefined;
} | {
    skipPrimary: boolean;
    beforeStatements: D1PreparedStatement[];
    afterStatements: D1PreparedStatement[];
    tables: string[];
    catalogPresent: true;
    viewRewrite: undefined;
} | {
    skipPrimary: boolean;
    beforeStatements: D1PreparedStatement[];
    afterStatements: D1PreparedStatement[];
    tables: string[];
    catalogPresent: true;
    viewRewrite: {
        triggerName: string;
        triggerSql: string;
        viewSql: string;
        returnsRows: boolean;
    };
}>;
export declare function catalogDefaultExecutionSql(value: string): string;
export declare function versionTriggerSingleColumnPrimaryKey(database: D1Database, table: string): Promise<string | null>;
