import{quoteIdentifier as m}from"./sql-quoting";import{EdgePgSemanticError as u}from"./semantic-error";import{applySchemaDefaultPrivileges as b,forgetDefaultPrivilegeCaches as $,schemaDefaultPrivilegeStatements as P}from"./default-privileges";import{d1CacheKey as U}from"./d1-cache-key";const x=3e5,w=new WeakMap;async function ee(e,t,i="edgepg"){return await I(e),t.action==="create"?v(e,t,i):t.action==="owner"?F(e,t):t.action==="rename"?J(e,t):z(e,t,i)}async function v(e,t,i){const r=t.name||t.owner;if(!r)throw new u("42601","CREATE SCHEMA requires a schema name or authorization role");try{await e.prepare(`INSERT INTO __edgepg_schemas(name, owner_name, oid)
      VALUES (?1, ?2, COALESCE((SELECT MAX(oid)+1 FROM __edgepg_schemas), 20000))`).bind(r,t.owner||i).run()}catch(n){if(t.ifExists&&/UNIQUE constraint failed/i.test(O(n)))return{command:"CREATE SCHEMA",rowCount:0};throw/UNIQUE constraint failed/i.test(O(n))?new u("42P06",`schema "${r}" already exists`):n}return await b(e,i,r),{command:"CREATE SCHEMA",rowCount:0}}async function te(e,t,i){await I(e);const r=t.name||t.owner;if(!r)throw new u("42601","CREATE SCHEMA requires a schema name or authorization role");if(await e.prepare("SELECT 1 AS present FROM __edgepg_schemas WHERE name=?1").bind(r).first()){if(t.ifExists)return[];throw new u("42P06",`schema "${r}" already exists`)}return[e.prepare(`INSERT INTO __edgepg_schemas(name, owner_name, oid)
      VALUES (?1, ?2, COALESCE((SELECT MAX(oid)+1 FROM __edgepg_schemas), 20000))`).bind(r,t.owner||i),...await P(e,i,r)]}async function F(e,t){const i=await e.prepare("SELECT owner_name FROM __edgepg_schemas WHERE name=?1").bind(t.name).first();if(!i)throw new u("3F000",`schema "${t.name}" does not exist`);return await B(e,t.name,i.owner_name,t.owner||"edgepg"),{command:"ALTER SCHEMA",rowCount:0}}async function B(e,t,i,r){if(i===r)return;const n=await h(e,"__edgepg_schema_privileges"),s=[];n&&s.push(e.prepare(`INSERT INTO __edgepg_schema_privileges
      (grantor,grantee,schema_name,privilege_type,is_grantable)
      SELECT CASE WHEN grantor=?2 THEN ?3 ELSE grantor END,
        CASE WHEN grantee=?2 THEN ?3 ELSE grantee END,
        schema_name,privilege_type,is_grantable
      FROM __edgepg_schema_privileges
      WHERE schema_name=?1 AND (grantor=?2 OR grantee=?2) AND 1=1
      ON CONFLICT(grantor,grantee,schema_name,privilege_type) DO UPDATE SET
        is_grantable=MAX(is_grantable,excluded.is_grantable)`).bind(t,i,r),e.prepare(`DELETE FROM __edgepg_schema_privileges
      WHERE schema_name=?1 AND (grantor=?2 OR grantee=?2)`).bind(t,i)),s.push(e.prepare("UPDATE __edgepg_schemas SET owner_name=?3 WHERE name=?1 AND owner_name=?2").bind(t,i,r)),await e.batch(s)}async function J(e,t){if(!t.newName)throw new u("42601","ALTER SCHEMA RENAME requires a new name");if(!await e.prepare("SELECT 1 AS present FROM __edgepg_schemas WHERE name=?1").bind(t.name).first())throw new u("3F000",`schema "${t.name}" does not exist`);if(await e.prepare("SELECT 1 AS present FROM __edgepg_schemas WHERE name=?1").bind(t.newName).first())throw new u("42P06",`schema "${t.newName}" already exists`);const n=[];n.push(...await X(e,t.name,t.newName)),await h(e,"__edgepg_schema_privileges")&&n.push(e.prepare("UPDATE __edgepg_schema_privileges SET schema_name=?2 WHERE schema_name=?1").bind(t.name,t.newName)),await h(e,"__edgepg_table_owners")&&n.push(e.prepare("UPDATE __edgepg_table_owners SET schema_name=?2 WHERE schema_name=?1").bind(t.name,t.newName)),await h(e,"__edgepg_table_privileges")&&n.push(e.prepare("UPDATE __edgepg_table_privileges SET schema_name=?2 WHERE schema_name=?1").bind(t.name,t.newName)),await h(e,"__edgepg_column_privileges")&&n.push(e.prepare("UPDATE __edgepg_column_privileges SET schema_name=?2 WHERE schema_name=?1").bind(t.name,t.newName)),await h(e,"__edgepg_default_privileges")&&n.push(e.prepare("UPDATE __edgepg_default_privileges SET schema_name=?2 WHERE schema_name=?1").bind(t.name,t.newName)),await h(e,"__edgepg_object_owners")&&n.push(e.prepare("UPDATE __edgepg_object_owners SET schema_name=?2 WHERE schema_name=?1").bind(t.name,t.newName)),n.push(...await L(e,t.name,t.newName,"rename"));const s=await H(e,`${t.name}__`),p=(await e.prepare(`SELECT name FROM sqlite_master WHERE type='table' AND name IN
    ('__edgepg_table_owners','__edgepg_table_privileges','__edgepg_column_privileges')`).all()).results.map(_=>_.name);for(const _ of s.filter(a=>a.type==="view"&&a.sql)){const a=A(_.name,`${t.name}__`,`${t.newName}__`);n.push(e.prepare(S(_.sql,_.name,a,"\0","\0")),e.prepare(`DROP VIEW ${m(_.name)}`));for(const o of p)n.push(e.prepare(`UPDATE ${m(o)}
      SET physical_name=?2 WHERE physical_name=?1`).bind(_.name,a))}for(const _ of s.filter(a=>a.type==="index"&&a.sql)){const a=A(_.name,`${t.name}__`,`${t.newName}__`);n.push(e.prepare(S(_.sql,_.name,a,"\0","\0")),e.prepare(`DROP INDEX ${m(_.name)}`))}n.push(...await D(e,t.name,t.newName,"rename",!0)),n.push(e.prepare("UPDATE __edgepg_schemas SET name=?2 WHERE name=?1").bind(t.name,t.newName));try{await e.batch(n)}catch(_){throw/already exists|UNIQUE constraint failed/i.test(O(_))?new u("42P06",`schema "${t.newName}" already exists`):_}return $(e),{command:"ALTER SCHEMA",rowCount:0}}async function X(e,t,i){const r=await e.prepare(`SELECT name FROM sqlite_master WHERE type='table' AND name IN
    ('__edgepg_routines','__edgepg_triggers','__edgepg_rls_tables','__edgepg_policies')`).all(),n=new Set(r.results.map(a=>a.name)),s=[],p=`"${t.replaceAll('"','""')}".`,_=`"${i.replaceAll('"','""')}".`;return n.has("__edgepg_routines")&&s.push(e.prepare(`UPDATE __edgepg_routines SET
    display_name=replace(display_name, ?1, ?2),
    definition=replace(replace(definition, ?3, ?4), ?1, ?2)
    WHERE display_name LIKE ?5`).bind(`${t}.`,`${i}.`,p,_,`${t}.%`)),n.has("__edgepg_triggers")&&s.push(e.prepare(`UPDATE __edgepg_triggers SET
    display_name=replace(display_name, ?1, ?2),
    command_json=replace(replace(command_json, ?3, ?4), ?1, ?2),
    definition=replace(replace(definition, ?3, ?4), ?1, ?2)
    WHERE display_name LIKE ?5`).bind(`${t}.`,`${i}.`,p,_,`${t}.%`)),n.has("__edgepg_rls_tables")&&s.push(e.prepare(`UPDATE __edgepg_rls_tables
    SET display_name=replace(display_name, ?1, ?2) WHERE display_name LIKE ?3`).bind(`${t}.`,`${i}.`,`${t}.%`)),n.has("__edgepg_policies")&&s.push(e.prepare(`UPDATE __edgepg_policies SET
    display_table_name=replace(display_table_name, ?1, ?2),
    definition=replace(replace(definition, ?3, ?4), ?1, ?2)
    WHERE display_table_name LIKE ?5`).bind(`${t}.`,`${i}.`,p,_,`${t}.%`)),s}async function N(e,t,i){const r=await e.prepare(`SELECT name FROM sqlite_master WHERE type='table' AND name IN
    ('__edgepg_routines','__edgepg_triggers','__edgepg_rls_tables','__edgepg_policies')`).all(),n=new Set(r.results.map(a=>a.name)),s=[["__edgepg_routines","display_name"],["__edgepg_triggers","display_name"],["__edgepg_rls_tables","display_name"],["__edgepg_policies","display_table_name"]],p=[],_=[];for(const[a,o]of s){if(!n.has(a))continue;if(i==="delete"){p.push(e.prepare(`DELETE FROM ${m(a)}
        WHERE ${m(o)} LIKE ?1`).bind(`${t}.%`));continue}await e.prepare(`SELECT 1 AS present FROM ${m(a)}
      WHERE ${m(o)} LIKE ?1 LIMIT 1`).bind(`${t}.%`).first()&&_.push(a)}return{statements:p,sources:_}}async function z(e,t,i){if(["pg_catalog","information_schema"].includes(t.name))throw new u("2BP01",`cannot drop schema ${t.name} because system objects depend on it`);if(!await e.prepare("SELECT 1 AS present FROM __edgepg_schemas WHERE name=?1").bind(t.name).first()){if(t.ifExists)return{command:"DROP SCHEMA",rowCount:0,notices:[{severity:"NOTICE",code:"00000",message:`schema "${t.name}" does not exist, skipping`}]};throw new u("3F000",`schema "${t.name}" does not exist`)}const n=`${t.name}__`,s=await k(e,t.name),p=[],_=await W(e,n,n,"probe",p),a=await N(e,t.name,"probe");if(!t.cascade&&(s.length||_.length||a.sources.length)){const c=[...s.map(g=>`sqlite_master:${g.type}`),...p,...a.sources];throw new u("2BP01",`cannot drop schema ${t.name} because other objects depend on it`+(c.length?` (${[...new Set(c)].join(", ")})`:""))}const o=[];if(t.cascade){for(const c of s.filter(g=>g.type==="view"))o.push(e.prepare(`DROP VIEW IF EXISTS ${m(c.name)}`));for(const c of s.filter(g=>g.type==="index"&&g.sql))o.push(e.prepare(`DROP INDEX IF EXISTS ${m(c.name)}`));for(const c of s.filter(g=>g.type==="table"))o.push(e.prepare(`DROP TABLE IF EXISTS ${m(c.name)}`));o.push(...await W(e,n,n,"delete")),o.push(...(await N(e,t.name,"delete")).statements),o.push(...await D(e,t.name,t.name,"delete"))}await h(e,"__edgepg_schema_privileges")&&o.push(e.prepare("DELETE FROM __edgepg_schema_privileges WHERE schema_name=?1").bind(t.name)),await h(e,"__edgepg_default_privileges")&&o.push(e.prepare("DELETE FROM __edgepg_default_privileges WHERE schema_name=?1").bind(t.name)),await h(e,"__edgepg_object_owners")&&o.push(e.prepare("DELETE FROM __edgepg_object_owners WHERE schema_name=?1").bind(t.name)),o.push(...await L(e,t.name,t.name,"delete")),o.push(e.prepare("DELETE FROM __edgepg_schemas WHERE name=?1").bind(t.name)),await e.batch(o),$(e);const E=t.cascade?s.filter(c=>c.type==="table"||c.type==="view").map(c=>{const g=c.name.startsWith(n)?c.name.slice(n.length):c.name,l=t.name===i?g:`${t.name}.${g}`;return{severity:"NOTICE",code:"00000",message:`drop cascades to ${c.type} ${l}`}}):[];return{command:"DROP SCHEMA",rowCount:0,...E.length?{notices:E}:{}}}async function L(e,t,i,r){if(!await h(e,"__edgepg_comments"))return[];const s=["OBJECT_SCHEMA","OBJECT_SEQUENCE","OBJECT_MATVIEW","OBJECT_TABLE","OBJECT_VIEW","OBJECT_INDEX","OBJECT_COLUMN","OBJECT_DOMAIN","OBJECT_TYPE","OBJECT_AGGREGATE","OBJECT_FUNCTION","OBJECT_PROCEDURE","OBJECT_ROUTINE","OBJECT_COLLATION","OBJECT_CONVERSION","OBJECT_OPERATOR","OBJECT_OPFAMILY","OBJECT_OPCLASS","OBJECT_POLICY","OBJECT_TRIGGER","OBJECT_TABCONSTRAINT","OBJECT_TSPARSER","OBJECT_TSTEMPLATE","OBJECT_TSDICTIONARY","OBJECT_TSCONFIGURATION"].map(p=>`'${p}'`).join(",");return r==="delete"?[e.prepare(`DELETE FROM __edgepg_comments
      WHERE object_type IN (${s}) AND json_extract(identity_json,'$[0]')=?1`).bind(t)]:[e.prepare(`UPDATE __edgepg_comments
      SET identity_json=json_set(identity_json,'$[0]',?2), updated_at=?3
      WHERE object_type IN (${s}) AND json_extract(identity_json,'$[0]')=?1`).bind(t,i,new Date().toISOString())]}async function D(e,t,i,r,n=!1){const s=await e.prepare(`SELECT name FROM sqlite_master WHERE type='table' AND name IN
    ('__edgepg_pg_tables','__edgepg_pg_sequences','__edgepg_pg_extensions','__edgepg_pg_objects',
      '__edgepg_materialized_views')`).all(),p=new Set(s.results.map(a=>a.name)),_=[];for(const a of p){if(r==="delete"){_.push(e.prepare(`DELETE FROM ${m(a)} WHERE schema_name=?1`).bind(t));continue}if(a==="__edgepg_materialized_views"){const g=`"${t.replaceAll('"','""')}".`,l=`"${i.replaceAll('"','""')}".`;_.push(e.prepare(`UPDATE __edgepg_materialized_views SET schema_name=?2,
        display_name=replace(display_name,?3,?4),
        query_sql=replace(query_sql,?5,?6),
        definition_sql=replace(definition_sql,?5,?6),
        definition_compact_sql=replace(definition_compact_sql,?5,?6)
        WHERE schema_name=?1`).bind(t,i,`${t}.`,`${i}.`,g,l));continue}const o=await e.prepare(`PRAGMA table_info(${m(a)})`).all(),E=o.results.some(g=>g.name==="definition"),c=o.results.some(g=>g.name==="alterations_json");if(!n&&a==="__edgepg_pg_objects"&&o.results.some(g=>g.name==="dependencies_json")){const g=await e.prepare(`SELECT rowid AS edgepg_rowid,dependencies_json
        FROM __edgepg_pg_objects`).all(),l=`${t}__`,f=`${i}__`;for(const d of g.results){const y=K(d.dependencies_json),C=y.map(T=>T.startsWith(l)?`${f}${T.slice(l.length)}`:T);C.every((T,j)=>T===y[j])||_.push(e.prepare("UPDATE __edgepg_pg_objects SET dependencies_json=?2 WHERE rowid=?1").bind(d.edgepg_rowid,JSON.stringify(C)))}}if(E){const g=await e.prepare(`SELECT rowid AS edgepg_rowid,definition
          ${c?",alterations_json":""}
        FROM ${m(a)} WHERE schema_name=?1`).bind(t).all();for(const l of g.results){const f=l.definition===null?null:R(l.definition,t,i),d=c&&l.alterations_json!==null&&l.alterations_json!==void 0?Q(l.alterations_json,t,i):l.alterations_json??null;_.push(e.prepare(`UPDATE ${m(a)} SET schema_name=?2,definition=?3
            ${c?",alterations_json=?4":""}
          WHERE rowid=?1`).bind(l.edgepg_rowid,i,f,...c?[d]:[]))}}else _.push(e.prepare(`UPDATE ${m(a)} SET schema_name=?2 WHERE schema_name=?1`).bind(t,i))}return _}async function I(e){const t=U(e),i=w.get(t);if(i?.pending)return i.pending;if(i&&i.expiresAt>Date.now())return;const r=G(e);w.set(t,{expiresAt:0,pending:r});try{await r,w.set(t,{expiresAt:Date.now()+x})}catch(n){throw w.delete(t),n}}async function G(e){await e.prepare(`CREATE TABLE IF NOT EXISTS __edgepg_schemas (
    name TEXT PRIMARY KEY, owner_name TEXT NOT NULL, oid INTEGER UNIQUE,
    acl_initialized INTEGER NOT NULL DEFAULT 0,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
  )`).run();const t=await e.prepare("PRAGMA table_info('__edgepg_schemas')").all();t.results.some(r=>r.name==="oid")||await e.prepare("ALTER TABLE __edgepg_schemas ADD COLUMN oid INTEGER").run(),t.results.some(r=>r.name==="acl_initialized")||await e.prepare("ALTER TABLE __edgepg_schemas ADD COLUMN acl_initialized INTEGER NOT NULL DEFAULT 0").run(),await e.prepare(`INSERT OR IGNORE INTO __edgepg_schemas(name, owner_name, oid) VALUES
    ('public', 'edgepg', 2200), ('pg_catalog', 'edgepg', 11), ('information_schema', 'edgepg', 13207)`).run(),await e.prepare(`UPDATE __edgepg_schemas SET oid=CASE name
    WHEN 'public' THEN 2200 WHEN 'pg_catalog' THEN 11 WHEN 'information_schema' THEN 13207 END
    WHERE oid IS NULL AND name IN ('public','pg_catalog','information_schema')`).run();const i=(await e.prepare("SELECT name FROM __edgepg_schemas WHERE oid IS NULL ORDER BY name").all()).results;for(const r of i)await e.prepare(`UPDATE __edgepg_schemas
    SET oid=COALESCE((SELECT MAX(oid)+1 FROM __edgepg_schemas), 20000) WHERE name=?1`).bind(r.name).run();await e.prepare("CREATE UNIQUE INDEX IF NOT EXISTS __edgepg_schemas_oid ON __edgepg_schemas(oid)").run()}async function k(e,t){const i=await H(e,`${t}__`);try{const r=await e.prepare("SELECT physical_name FROM __edgepg_pg_tables WHERE schema_name=?1").bind(t).all(),n=new Set(i.map(s=>s.name));for(const s of r.results){if(n.has(s.physical_name))continue;const p=await e.prepare(`SELECT type,name,sql FROM sqlite_master
        WHERE name=?1 AND type IN ('table','view')`).bind(s.physical_name).first();p&&(i.push(p),n.add(p.name))}return i}catch(r){if(/no such table:\s*__edgepg_pg_tables/iu.test(r instanceof Error?r.message:String(r)))return i;throw r}}function ne(e,t){if(e.action==="drop")return e.cascade?[...t.filter(s=>s.type==="view").map(s=>({kind:"drop-object",objectType:"view",name:s.name})),...t.filter(s=>s.type==="index"&&s.sql).map(s=>({kind:"drop-object",objectType:"index",name:s.name})),...t.filter(s=>s.type==="table").map(s=>({kind:"drop-table",name:s.name}))]:[];if(e.action!=="rename"||!e.newName)return[];const i=`${e.name}__`,r=`${e.newName}__`,n=[];for(const s of t.filter(p=>p.type==="view"&&p.sql)){const p=A(s.name,i,r);n.push({kind:"create-object",objectType:"view",name:p,sql:S(s.sql,s.name,p,"\0","\0")}),n.push({kind:"drop-object",objectType:"view",name:s.name})}for(const s of t.filter(p=>p.type==="index"&&p.sql)){const p=A(s.name,i,r);n.push({kind:"create-object",objectType:"index",name:p,sql:S(s.sql,s.name,p,"\0","\0")}),n.push({kind:"drop-object",objectType:"index",name:s.name})}return n}async function H(e,t){return(await e.prepare(`SELECT type, name, sql FROM sqlite_master
    WHERE substr(name, 1, ?2) = ?1 AND substr(name, 1, 7) <> 'sqlite_'
    ORDER BY CASE type WHEN 'table' THEN 1 WHEN 'view' THEN 2 ELSE 3 END, name`).bind(t,t.length).all()).results.filter(r=>r.type!=="trigger")}async function W(e,t,i,r,n=[]){const s=await e.prepare(`SELECT master.name AS table_name,column_info.name AS column_name,
      column_info.type AS column_type
    FROM sqlite_master AS master JOIN pragma_table_info(master.name) AS column_info
    WHERE master.type='table' AND master.name LIKE '__edgepg_%'
    ORDER BY master.name,column_info.cid`).all(),p=new Map;for(const a of s.results){const o=p.get(a.table_name)||[];o.push({name:a.column_name,type:a.column_type}),p.set(a.table_name,o)}const _=[];for(const[a,o]of p){if(a.startsWith("__edgepg_sp_")||a.startsWith("__edgepg_base_")||["__edgepg_schemas","__edgepg_schema_privileges"].includes(a)||r==="probe"&&a==="__edgepg_table_versions")continue;const E=o.filter(l=>/TEXT|CHAR|CLOB/i.test(l.type)&&(!["__edgepg_table_owners","__edgepg_table_privileges","__edgepg_column_privileges"].includes(a)||l.name==="physical_name"));if(!E.length)continue;const c=E.map((l,f)=>`instr(${m(l.name)}, ?${f+1}) = 1`).join(" OR ");if(r==="probe"){await e.prepare(`SELECT 1 AS present FROM ${m(a)} WHERE ${c} LIMIT 1`).bind(...E.map(()=>t)).first()&&(_.push(e.prepare("SELECT 1")),n.push(a));continue}if(r==="delete"){_.push(e.prepare(`DELETE FROM ${m(a)} WHERE ${c}`).bind(...E.map(()=>t)));continue}const g=E.map(l=>{const f=m(l.name);return`${f}=CASE WHEN instr(${f},?1)=1 THEN ?2 || substr(${f},?3) ELSE ${f} END`}).join(",");_.push(e.prepare(`UPDATE ${m(a)} SET ${g}
      WHERE ${E.map(l=>`instr(${m(l.name)},?1)=1`).join(" OR ")}`).bind(t,i,[...t].length+1))}return _}function S(e,t,i,r,n){let s="",p=!1;for(let _=0;_<e.length;){if(e.startsWith("--",_)){const E=e.indexOf(`
`,_+2),c=E<0?e.length:E;s+=e.slice(_,c),_=c;continue}if(e.startsWith("/*",_)){let E=1,c=_+2;for(;c<e.length&&E>0;)e.startsWith("/*",c)?(E+=1,c+=2):e.startsWith("*/",c)?(E-=1,c+=2):c+=1;s+=e.slice(_,c),_=c;continue}if(e[_]==="'"){let E=_+1;for(;E<e.length;){if(e[E]!=="'"){E+=1;continue}if(e[E+1]==="'"){E+=2;continue}E+=1;break}s+=e.slice(_,E),_=E;continue}const a=M(e,_);if(!a){s+=e[_],_+=1;continue}let o;a.value===t?(o=i,p=!0):a.value.startsWith(r)&&(o=`${n}${a.value.slice(r.length)}`),o===void 0?s+=e.slice(_,a.end):s+=a.quoted||!/^[a-z_][a-z0-9_$]*$/u.test(o)?m(o):o,_=a.end}if(!p)throw new u("XX000",`stored definition for ${t} is invalid`);return s}function A(e,t,i){return e.startsWith(t)?`${i}${e.slice(t.length)}`:e}function R(e,t,i){let r="";for(let n=0;n<e.length;){if(e.startsWith("--",n)){const a=e.indexOf(`
`,n+2),o=a<0?e.length:a;r+=e.slice(n,o),n=o;continue}if(e.startsWith("/*",n)){let a=1,o=n+2;for(;o<e.length&&a>0;)e.startsWith("/*",o)?(a+=1,o+=2):e.startsWith("*/",o)?(a-=1,o+=2):o+=1;r+=e.slice(n,o),n=o;continue}if(e[n]==="'"){let a=n+1;for(;a<e.length;){if(e[a]!=="'"){a+=1;continue}if(e[a+1]==="'"){a+=2;continue}a+=1;break}r+=e.slice(n,a),n=a;continue}const s=e.slice(n).match(/^\$[A-Za-z_][A-Za-z0-9_]*\$|^\$\$/)?.[0];if(s){const a=e.indexOf(s,n+s.length),o=a<0?e.length:a+s.length;r+=e.slice(n,o),n=o;continue}const p=M(e,n);if(!p){r+=e[n],n+=1;continue}let _=p.end;for(;_<e.length&&/\s/u.test(e[_]);)_+=1;if(p.value===t&&e[_]==="."){r+=p.quoted||!/^[a-z_][a-z0-9_$]*$/u.test(i)?m(i):i,r+=e.slice(p.end,_+1),n=_+1;continue}r+=e.slice(n,p.end),n=p.end}return r}function M(e,t){if(e[t]==='"'){let r="",n=t+1;for(;n<e.length;){if(e[n]!=='"'){r+=e[n],n+=1;continue}if(e[n+1]==='"'){r+='"',n+=2;continue}return{value:r,end:n+1,quoted:!0}}return null}const i=e.slice(t).match(/^[A-Za-z_][A-Za-z0-9_$]*/u)?.[0];return i?{value:i,end:t+i.length,quoted:!1}:null}function Q(e,t,i){try{const r=n=>typeof n=="string"?R(n,t,i):Array.isArray(n)?n.map(r):n&&typeof n=="object"?Object.fromEntries(Object.entries(n).map(([s,p])=>[s,r(p)])):n;return JSON.stringify(r(JSON.parse(e)))}catch{return R(e,t,i)}}function K(e){let t;try{t=JSON.parse(e)}catch{throw new u("XX000","invalid PostgreSQL object dependency metadata")}if(!Array.isArray(t)||!t.every(i=>typeof i=="string"))throw new u("XX000","invalid PostgreSQL object dependency metadata");return t}function O(e){return e instanceof Error?e.message:String(e)}async function h(e,t){return!!await e.prepare("SELECT 1 AS present FROM sqlite_master WHERE type='table' AND name=?1").bind(t).first()}export{B as changeSchemaOwner,te as createSchemaStatements,I as ensureSchemaCatalog,ee as executeSchemaCommand,ne as schemaPhysicalMutations,k as schemaPhysicalObjects};
