import{quoteIdentifier as m}from"./sql-quoting";import{EdgePgSemanticError as u}from"./semantic-error";import{applySchemaDefaultPrivileges as j,forgetDefaultPrivilegeCaches as N,schemaDefaultPrivilegeStatements as P}from"./default-privileges";import{d1CacheKey as x}from"./d1-cache-key";const U=3e5,w=new WeakMap;async function ee(e,t,i="edgepg"){return await H(e),t.action==="create"?v(e,t,i):t.action==="owner"?F(e,t):t.action==="rename"?J(e,t):z(e,t,i)}async function v(e,t,i){const s=t.name||t.owner;if(!s)throw new u("42601","CREATE SCHEMA requires a schema name or authorization role");try{await e.prepare(`INSERT INTO __edgepg_schemas(name, owner_name, oid)
      VALUES (?1, ?2, COALESCE((SELECT MAX(oid)+1 FROM __edgepg_schemas), 20000))`).bind(s,t.owner||i).run()}catch(n){if(t.ifExists&&/UNIQUE constraint failed/i.test(O(n)))return{command:"CREATE SCHEMA",rowCount:0};throw/UNIQUE constraint failed/i.test(O(n))?new u("42P06",`schema "${s}" already exists`):n}return await j(e,i,s),{command:"CREATE SCHEMA",rowCount:0}}async function te(e,t,i){await H(e);const s=t.name||t.owner;if(!s)throw new u("42601","CREATE SCHEMA requires a schema name or authorization role");if(await e.prepare("SELECT 1 AS present FROM __edgepg_schemas WHERE name=?1").bind(s).first()){if(t.ifExists)return[];throw new u("42P06",`schema "${s}" already exists`)}return[e.prepare(`INSERT INTO __edgepg_schemas(name, owner_name, oid)
      VALUES (?1, ?2, COALESCE((SELECT MAX(oid)+1 FROM __edgepg_schemas), 20000))`).bind(s,t.owner||i),...await P(e,i,s)]}async function F(e,t){const i=await e.prepare("SELECT owner_name FROM __edgepg_schemas WHERE name=?1").bind(t.name).first();if(!i)throw new u("3F000",`schema "${t.name}" does not exist`);return await B(e,t.name,i.owner_name,t.owner||"edgepg"),{command:"ALTER SCHEMA",rowCount:0}}async function B(e,t,i,s){if(i===s)return;const n=await h(e,"__edgepg_schema_privileges"),r=[];n&&r.push(e.prepare(`INSERT INTO __edgepg_schema_privileges
      (grantor,grantee,schema_name,privilege_type,is_grantable)
      SELECT CASE WHEN grantor=?2 THEN ?3 ELSE grantor END,
        CASE WHEN grantee=?2 THEN ?3 ELSE grantee END,
        schema_name,privilege_type,is_grantable
      FROM __edgepg_schema_privileges
      WHERE schema_name=?1 AND (grantor=?2 OR grantee=?2) AND 1=1
      ON CONFLICT(grantor,grantee,schema_name,privilege_type) DO UPDATE SET
        is_grantable=MAX(is_grantable,excluded.is_grantable)`).bind(t,i,s),e.prepare(`DELETE FROM __edgepg_schema_privileges
      WHERE schema_name=?1 AND (grantor=?2 OR grantee=?2)`).bind(t,i)),r.push(e.prepare("UPDATE __edgepg_schemas SET owner_name=?3 WHERE name=?1 AND owner_name=?2").bind(t,i,s)),await e.batch(r)}async function J(e,t){if(!t.newName)throw new u("42601","ALTER SCHEMA RENAME requires a new name");if(!await e.prepare("SELECT 1 AS present FROM __edgepg_schemas WHERE name=?1").bind(t.name).first())throw new u("3F000",`schema "${t.name}" does not exist`);if(await e.prepare("SELECT 1 AS present FROM __edgepg_schemas WHERE name=?1").bind(t.newName).first())throw new u("42P06",`schema "${t.newName}" already exists`);const n=[];n.push(...await X(e,t.name,t.newName)),await h(e,"__edgepg_schema_privileges")&&n.push(e.prepare("UPDATE __edgepg_schema_privileges SET schema_name=?2 WHERE schema_name=?1").bind(t.name,t.newName)),await h(e,"__edgepg_table_owners")&&n.push(e.prepare("UPDATE __edgepg_table_owners SET schema_name=?2 WHERE schema_name=?1").bind(t.name,t.newName)),await h(e,"__edgepg_table_privileges")&&n.push(e.prepare("UPDATE __edgepg_table_privileges SET schema_name=?2 WHERE schema_name=?1").bind(t.name,t.newName)),await h(e,"__edgepg_column_privileges")&&n.push(e.prepare("UPDATE __edgepg_column_privileges SET schema_name=?2 WHERE schema_name=?1").bind(t.name,t.newName)),await h(e,"__edgepg_default_privileges")&&n.push(e.prepare("UPDATE __edgepg_default_privileges SET schema_name=?2 WHERE schema_name=?1").bind(t.name,t.newName)),await h(e,"__edgepg_object_owners")&&n.push(e.prepare("UPDATE __edgepg_object_owners SET schema_name=?2 WHERE schema_name=?1").bind(t.name,t.newName)),n.push(...await L(e,t.name,t.newName,"rename"));const r=await I(e,`${t.name}__`),o=(await e.prepare(`SELECT name FROM sqlite_master WHERE type='table' AND name IN
    ('__edgepg_table_owners','__edgepg_table_privileges','__edgepg_column_privileges')`).all()).results.map(_=>_.name);for(const _ of r.filter(a=>a.type==="view"&&a.sql)){const a=A(_.name,`${t.name}__`,`${t.newName}__`);n.push(e.prepare(S(_.sql,_.name,a,"\0","\0")),e.prepare(`DROP VIEW ${m(_.name)}`));for(const p of o)n.push(e.prepare(`UPDATE ${m(p)}
      SET physical_name=?2 WHERE physical_name=?1`).bind(_.name,a))}for(const _ of r.filter(a=>a.type==="index"&&a.sql)){const a=A(_.name,`${t.name}__`,`${t.newName}__`);n.push(e.prepare(S(_.sql,_.name,a,"\0","\0")),e.prepare(`DROP INDEX ${m(_.name)}`))}n.push(...await D(e,t.name,t.newName,"rename",!0)),n.push(e.prepare("UPDATE __edgepg_schemas SET name=?2 WHERE name=?1").bind(t.name,t.newName));try{await e.batch(n)}catch(_){throw/already exists|UNIQUE constraint failed/i.test(O(_))?new u("42P06",`schema "${t.newName}" already exists`):_}return N(e),{command:"ALTER SCHEMA",rowCount:0}}async function X(e,t,i){const s=await e.prepare(`SELECT name FROM sqlite_master WHERE type='table' AND name IN
    ('__edgepg_routines','__edgepg_triggers','__edgepg_rls_tables','__edgepg_policies')`).all(),n=new Set(s.results.map(a=>a.name)),r=[],o=`"${t.replaceAll('"','""')}".`,_=`"${i.replaceAll('"','""')}".`;return n.has("__edgepg_routines")&&r.push(e.prepare(`UPDATE __edgepg_routines SET
    display_name=replace(display_name, ?1, ?2),
    definition=replace(replace(definition, ?3, ?4), ?1, ?2)
    WHERE display_name LIKE ?5`).bind(`${t}.`,`${i}.`,o,_,`${t}.%`)),n.has("__edgepg_triggers")&&r.push(e.prepare(`UPDATE __edgepg_triggers SET
    display_name=replace(display_name, ?1, ?2),
    command_json=replace(replace(command_json, ?3, ?4), ?1, ?2),
    definition=replace(replace(definition, ?3, ?4), ?1, ?2)
    WHERE display_name LIKE ?5`).bind(`${t}.`,`${i}.`,o,_,`${t}.%`)),n.has("__edgepg_rls_tables")&&r.push(e.prepare(`UPDATE __edgepg_rls_tables
    SET display_name=replace(display_name, ?1, ?2) WHERE display_name LIKE ?3`).bind(`${t}.`,`${i}.`,`${t}.%`)),n.has("__edgepg_policies")&&r.push(e.prepare(`UPDATE __edgepg_policies SET
    display_table_name=replace(display_table_name, ?1, ?2),
    definition=replace(replace(definition, ?3, ?4), ?1, ?2)
    WHERE display_table_name LIKE ?5`).bind(`${t}.`,`${i}.`,o,_,`${t}.%`)),r}async function $(e,t,i){const s=await e.prepare(`SELECT name FROM sqlite_master WHERE type='table' AND name IN
    ('__edgepg_routines','__edgepg_triggers','__edgepg_rls_tables','__edgepg_policies')`).all(),n=new Set(s.results.map(a=>a.name)),r=[["__edgepg_routines","display_name"],["__edgepg_triggers","display_name"],["__edgepg_rls_tables","display_name"],["__edgepg_policies","display_table_name"]],o=[],_=[];for(const[a,p]of r){if(!n.has(a))continue;if(i==="delete"){o.push(e.prepare(`DELETE FROM ${m(a)}
        WHERE ${m(p)} LIKE ?1`).bind(`${t}.%`));continue}await e.prepare(`SELECT 1 AS present FROM ${m(a)}
      WHERE ${m(p)} LIKE ?1 LIMIT 1`).bind(`${t}.%`).first()&&_.push(a)}return{statements:o,sources:_}}async function z(e,t,i){if(["pg_catalog","information_schema"].includes(t.name))throw new u("2BP01",`cannot drop schema ${t.name} because system objects depend on it`);if(!await e.prepare("SELECT 1 AS present FROM __edgepg_schemas WHERE name=?1").bind(t.name).first()){if(t.ifExists)return{command:"DROP SCHEMA",rowCount:0,notices:[{severity:"NOTICE",code:"00000",message:`schema "${t.name}" does not exist, skipping`}]};throw new u("3F000",`schema "${t.name}" does not exist`)}const n=`${t.name}__`,r=await k(e,t.name),o=[],_=await W(e,n,n,"probe",o),a=await $(e,t.name,"probe");if(!t.cascade&&(r.length||_.length||a.sources.length)){const E=[...r.map(g=>`sqlite_master:${g.type}`),...o,...a.sources];throw new u("2BP01",`cannot drop schema ${t.name} because other objects depend on it`+(E.length?` (${[...new Set(E)].join(", ")})`:""))}const p=[];if(t.cascade){for(const E of r.filter(g=>g.type==="view"))p.push(e.prepare(`DROP VIEW IF EXISTS ${m(E.name)}`));for(const E of r.filter(g=>g.type==="index"&&g.sql))p.push(e.prepare(`DROP INDEX IF EXISTS ${m(E.name)}`));for(const E of r.filter(g=>g.type==="table"))p.push(e.prepare(`DROP TABLE IF EXISTS ${m(E.name)}`));p.push(...await W(e,n,n,"delete")),p.push(...(await $(e,t.name,"delete")).statements),p.push(...await D(e,t.name,t.name,"delete"))}await h(e,"__edgepg_schema_privileges")&&p.push(e.prepare("DELETE FROM __edgepg_schema_privileges WHERE schema_name=?1").bind(t.name)),await h(e,"__edgepg_default_privileges")&&p.push(e.prepare("DELETE FROM __edgepg_default_privileges WHERE schema_name=?1").bind(t.name)),await h(e,"__edgepg_object_owners")&&p.push(e.prepare("DELETE FROM __edgepg_object_owners WHERE schema_name=?1").bind(t.name)),p.push(...await L(e,t.name,t.name,"delete")),p.push(e.prepare("DELETE FROM __edgepg_schemas WHERE name=?1").bind(t.name)),await e.batch(p),N(e);const c=t.cascade?r.filter(E=>E.type==="table"||E.type==="view").map(E=>{const g=E.name.startsWith(n)?E.name.slice(n.length):E.name,l=t.name===i?g:`${t.name}.${g}`;return{severity:"NOTICE",code:"00000",message:`drop cascades to ${E.type} ${l}`}}):[];return{command:"DROP SCHEMA",rowCount:0,...c.length?{notices:c}:{}}}async function L(e,t,i,s){if(!await h(e,"__edgepg_comments"))return[];const r=["OBJECT_SCHEMA","OBJECT_SEQUENCE","OBJECT_MATVIEW","OBJECT_TABLE","OBJECT_VIEW","OBJECT_INDEX","OBJECT_COLUMN","OBJECT_DOMAIN","OBJECT_TYPE","OBJECT_AGGREGATE","OBJECT_FUNCTION","OBJECT_PROCEDURE","OBJECT_ROUTINE","OBJECT_COLLATION","OBJECT_CONVERSION","OBJECT_OPERATOR","OBJECT_OPFAMILY","OBJECT_OPCLASS","OBJECT_POLICY","OBJECT_TRIGGER","OBJECT_TABCONSTRAINT","OBJECT_TSPARSER","OBJECT_TSTEMPLATE","OBJECT_TSDICTIONARY","OBJECT_TSCONFIGURATION"].map(o=>`'${o}'`).join(",");return s==="delete"?[e.prepare(`DELETE FROM __edgepg_comments
      WHERE object_type IN (${r}) AND json_extract(identity_json,'$[0]')=?1`).bind(t)]:[e.prepare(`UPDATE __edgepg_comments
      SET identity_json=json_set(identity_json,'$[0]',?2), updated_at=?3
      WHERE object_type IN (${r}) AND json_extract(identity_json,'$[0]')=?1`).bind(t,i,new Date().toISOString())]}async function D(e,t,i,s,n=!1){const r=await e.prepare(`SELECT name FROM sqlite_master WHERE type='table' AND name IN
    ('__edgepg_pg_tables','__edgepg_pg_sequences','__edgepg_pg_extensions','__edgepg_pg_objects',
      '__edgepg_materialized_views')`).all(),o=new Set(r.results.map(a=>a.name)),_=[];for(const a of o){if(s==="delete"){_.push(e.prepare(`DELETE FROM ${m(a)} WHERE schema_name=?1`).bind(t));continue}if(a==="__edgepg_materialized_views"){const g=`"${t.replaceAll('"','""')}".`,l=`"${i.replaceAll('"','""')}".`;_.push(e.prepare(`UPDATE __edgepg_materialized_views SET schema_name=?2,
        display_name=replace(display_name,?3,?4),
        query_sql=replace(query_sql,?5,?6),
        definition_sql=replace(definition_sql,?5,?6),
        definition_compact_sql=replace(definition_compact_sql,?5,?6)
        WHERE schema_name=?1`).bind(t,i,`${t}.`,`${i}.`,g,l));continue}const p=await e.prepare(`PRAGMA table_info(${m(a)})`).all(),c=p.results.some(g=>g.name==="definition"),E=p.results.some(g=>g.name==="alterations_json");if(!n&&a==="__edgepg_pg_objects"&&p.results.some(g=>g.name==="dependencies_json")){const g=await e.prepare(`SELECT rowid AS edgepg_rowid,dependencies_json
        FROM __edgepg_pg_objects`).all(),l=`${t}__`,f=`${i}__`;for(const d of g.results){const y=Y(d.dependencies_json),C=y.map(T=>T.startsWith(l)?`${f}${T.slice(l.length)}`:T);C.every((T,b)=>T===y[b])||_.push(e.prepare("UPDATE __edgepg_pg_objects SET dependencies_json=?2 WHERE rowid=?1").bind(d.edgepg_rowid,JSON.stringify(C)))}}if(c){const g=await e.prepare(`SELECT rowid AS edgepg_rowid,definition
          ${E?",alterations_json":""}
        FROM ${m(a)} WHERE schema_name=?1`).bind(t).all();for(const l of g.results){const f=l.definition===null?null:R(l.definition,t,i),d=E&&l.alterations_json!==null&&l.alterations_json!==void 0?Q(l.alterations_json,t,i):l.alterations_json??null;_.push(e.prepare(`UPDATE ${m(a)} SET schema_name=?2,definition=?3
            ${E?",alterations_json=?4":""}
          WHERE rowid=?1`).bind(l.edgepg_rowid,i,f,...E?[d]:[]))}}else _.push(e.prepare(`UPDATE ${m(a)} SET schema_name=?2 WHERE schema_name=?1`).bind(t,i))}return _}async function H(e){const t=x(e),i=w.get(t);if(i?.pending)return i.pending;if(i&&i.expiresAt>Date.now())return;const s=G(e);w.set(t,{expiresAt:0,pending:s});try{await s,w.set(t,{expiresAt:Date.now()+U})}catch(n){throw w.delete(t),n}}async function G(e){await e.prepare(`CREATE TABLE IF NOT EXISTS __edgepg_schemas (
    name TEXT PRIMARY KEY, owner_name TEXT NOT NULL, oid INTEGER UNIQUE,
    acl_initialized INTEGER NOT NULL DEFAULT 0,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
  )`).run();const t=await e.prepare("PRAGMA table_info('__edgepg_schemas')").all();t.results.some(s=>s.name==="oid")||await e.prepare("ALTER TABLE __edgepg_schemas ADD COLUMN oid INTEGER").run(),t.results.some(s=>s.name==="acl_initialized")||await e.prepare("ALTER TABLE __edgepg_schemas ADD COLUMN acl_initialized INTEGER NOT NULL DEFAULT 0").run(),await e.prepare(`INSERT OR IGNORE INTO __edgepg_schemas(name, owner_name, oid) VALUES
    ('public', 'edgepg', 2200), ('pg_catalog', 'edgepg', 11), ('information_schema', 'edgepg', 13207)`).run(),await e.prepare(`UPDATE __edgepg_schemas SET oid=CASE name
    WHEN 'public' THEN 2200 WHEN 'pg_catalog' THEN 11 WHEN 'information_schema' THEN 13207 END
    WHERE oid IS NULL AND name IN ('public','pg_catalog','information_schema')`).run();const i=(await e.prepare("SELECT name FROM __edgepg_schemas WHERE oid IS NULL ORDER BY name").all()).results;for(const s of i)await e.prepare(`UPDATE __edgepg_schemas
    SET oid=COALESCE((SELECT MAX(oid)+1 FROM __edgepg_schemas), 20000) WHERE name=?1`).bind(s.name).run();await e.prepare("CREATE UNIQUE INDEX IF NOT EXISTS __edgepg_schemas_oid ON __edgepg_schemas(oid)").run()}async function k(e,t){const i=`${t}__`;try{return(await e.prepare(`SELECT master.type,master.name,master.sql
      FROM sqlite_master AS master
      WHERE (substr(master.name,1,?2)=?1 OR (master.type IN ('table','view') AND EXISTS (
        SELECT 1 FROM __edgepg_pg_tables AS catalog
        WHERE catalog.physical_name=master.name AND catalog.schema_name=?3)))
        AND substr(master.name,1,7)<>'sqlite_' AND master.type IN ('table','view','index')
      ORDER BY CASE WHEN substr(master.name,1,?2)=?1 THEN 0 ELSE 1 END,
        CASE master.type WHEN 'table' THEN 1 WHEN 'view' THEN 2 ELSE 3 END,master.name`).bind(i,i.length,t).all()).results}catch(s){if(/no such table:\s*__edgepg_pg_tables/iu.test(s instanceof Error?s.message:String(s)))return I(e,i);throw s}}function ne(e,t){if(e.action==="drop")return e.cascade?[...t.filter(r=>r.type==="view").map(r=>({kind:"drop-object",objectType:"view",name:r.name})),...t.filter(r=>r.type==="index"&&r.sql).map(r=>({kind:"drop-object",objectType:"index",name:r.name})),...t.filter(r=>r.type==="table").map(r=>({kind:"drop-table",name:r.name}))]:[];if(e.action!=="rename"||!e.newName)return[];const i=`${e.name}__`,s=`${e.newName}__`,n=[];for(const r of t.filter(o=>o.type==="view"&&o.sql)){const o=A(r.name,i,s);n.push({kind:"create-object",objectType:"view",name:o,sql:S(r.sql,r.name,o,"\0","\0")}),n.push({kind:"drop-object",objectType:"view",name:r.name})}for(const r of t.filter(o=>o.type==="index"&&o.sql)){const o=A(r.name,i,s);n.push({kind:"create-object",objectType:"index",name:o,sql:S(r.sql,r.name,o,"\0","\0")}),n.push({kind:"drop-object",objectType:"index",name:r.name})}return n}async function I(e,t){return(await e.prepare(`SELECT type, name, sql FROM sqlite_master
    WHERE substr(name, 1, ?2) = ?1 AND substr(name, 1, 7) <> 'sqlite_'
    ORDER BY CASE type WHEN 'table' THEN 1 WHEN 'view' THEN 2 ELSE 3 END, name`).bind(t,t.length).all()).results.filter(s=>s.type!=="trigger")}async function W(e,t,i,s,n=[]){const r=await e.prepare(`SELECT master.name AS table_name,column_info.name AS column_name,
      column_info.type AS column_type
    FROM sqlite_master AS master JOIN pragma_table_info(master.name) AS column_info
    WHERE master.type='table' AND master.name LIKE '__edgepg_%'
    ORDER BY master.name,column_info.cid`).all(),o=new Map;for(const a of r.results){const p=o.get(a.table_name)||[];p.push({name:a.column_name,type:a.column_type}),o.set(a.table_name,p)}const _=[];for(const[a,p]of o){if(a.startsWith("__edgepg_sp_")||a.startsWith("__edgepg_base_")||["__edgepg_schemas","__edgepg_schema_privileges"].includes(a)||s==="probe"&&a==="__edgepg_table_versions")continue;const c=p.filter(l=>/TEXT|CHAR|CLOB/i.test(l.type)&&(!["__edgepg_table_owners","__edgepg_table_privileges","__edgepg_column_privileges"].includes(a)||l.name==="physical_name"));if(!c.length)continue;const E=c.map((l,f)=>`instr(${m(l.name)}, ?${f+1}) = 1`).join(" OR ");if(s==="probe"){await e.prepare(`SELECT 1 AS present FROM ${m(a)} WHERE ${E} LIMIT 1`).bind(...c.map(()=>t)).first()&&(_.push(e.prepare("SELECT 1")),n.push(a));continue}if(s==="delete"){_.push(e.prepare(`DELETE FROM ${m(a)} WHERE ${E}`).bind(...c.map(()=>t)));continue}const g=c.map(l=>{const f=m(l.name);return`${f}=CASE WHEN instr(${f},?1)=1 THEN ?2 || substr(${f},?3) ELSE ${f} END`}).join(",");_.push(e.prepare(`UPDATE ${m(a)} SET ${g}
      WHERE ${c.map(l=>`instr(${m(l.name)},?1)=1`).join(" OR ")}`).bind(t,i,[...t].length+1))}return _}function S(e,t,i,s,n){let r="",o=!1;for(let _=0;_<e.length;){if(e.startsWith("--",_)){const c=e.indexOf(`
`,_+2),E=c<0?e.length:c;r+=e.slice(_,E),_=E;continue}if(e.startsWith("/*",_)){let c=1,E=_+2;for(;E<e.length&&c>0;)e.startsWith("/*",E)?(c+=1,E+=2):e.startsWith("*/",E)?(c-=1,E+=2):E+=1;r+=e.slice(_,E),_=E;continue}if(e[_]==="'"){let c=_+1;for(;c<e.length;){if(e[c]!=="'"){c+=1;continue}if(e[c+1]==="'"){c+=2;continue}c+=1;break}r+=e.slice(_,c),_=c;continue}const a=M(e,_);if(!a){r+=e[_],_+=1;continue}let p;a.value===t?(p=i,o=!0):a.value.startsWith(s)&&(p=`${n}${a.value.slice(s.length)}`),p===void 0?r+=e.slice(_,a.end):r+=a.quoted||!/^[a-z_][a-z0-9_$]*$/u.test(p)?m(p):p,_=a.end}if(!o)throw new u("XX000",`stored definition for ${t} is invalid`);return r}function A(e,t,i){return e.startsWith(t)?`${i}${e.slice(t.length)}`:e}function R(e,t,i){let s="";for(let n=0;n<e.length;){if(e.startsWith("--",n)){const a=e.indexOf(`
`,n+2),p=a<0?e.length:a;s+=e.slice(n,p),n=p;continue}if(e.startsWith("/*",n)){let a=1,p=n+2;for(;p<e.length&&a>0;)e.startsWith("/*",p)?(a+=1,p+=2):e.startsWith("*/",p)?(a-=1,p+=2):p+=1;s+=e.slice(n,p),n=p;continue}if(e[n]==="'"){let a=n+1;for(;a<e.length;){if(e[a]!=="'"){a+=1;continue}if(e[a+1]==="'"){a+=2;continue}a+=1;break}s+=e.slice(n,a),n=a;continue}const r=e.slice(n).match(/^\$[A-Za-z_][A-Za-z0-9_]*\$|^\$\$/)?.[0];if(r){const a=e.indexOf(r,n+r.length),p=a<0?e.length:a+r.length;s+=e.slice(n,p),n=p;continue}const o=M(e,n);if(!o){s+=e[n],n+=1;continue}let _=o.end;for(;_<e.length&&/\s/u.test(e[_]);)_+=1;if(o.value===t&&e[_]==="."){s+=o.quoted||!/^[a-z_][a-z0-9_$]*$/u.test(i)?m(i):i,s+=e.slice(o.end,_+1),n=_+1;continue}s+=e.slice(n,o.end),n=o.end}return s}function M(e,t){if(e[t]==='"'){let s="",n=t+1;for(;n<e.length;){if(e[n]!=='"'){s+=e[n],n+=1;continue}if(e[n+1]==='"'){s+='"',n+=2;continue}return{value:s,end:n+1,quoted:!0}}return null}const i=e.slice(t).match(/^[A-Za-z_][A-Za-z0-9_$]*/u)?.[0];return i?{value:i,end:t+i.length,quoted:!1}:null}function Q(e,t,i){try{const s=n=>typeof n=="string"?R(n,t,i):Array.isArray(n)?n.map(s):n&&typeof n=="object"?Object.fromEntries(Object.entries(n).map(([r,o])=>[r,s(o)])):n;return JSON.stringify(s(JSON.parse(e)))}catch{return R(e,t,i)}}function Y(e){let t;try{t=JSON.parse(e)}catch{throw new u("XX000","invalid PostgreSQL object dependency metadata")}if(!Array.isArray(t)||!t.every(i=>typeof i=="string"))throw new u("XX000","invalid PostgreSQL object dependency metadata");return t}function O(e){return e instanceof Error?e.message:String(e)}async function h(e,t){return!!await e.prepare("SELECT 1 AS present FROM sqlite_master WHERE type='table' AND name=?1").bind(t).first()}export{B as changeSchemaOwner,te as createSchemaStatements,H as ensureSchemaCatalog,ee as executeSchemaCommand,ne as schemaPhysicalMutations,k as schemaPhysicalObjects};
