import{quoteLiteral as T}from"./sql-quoting";import{physicalRelationNameFromParts as p}from"./relation-identity";import{EdgePgSemanticError as n}from"./semantic-error";import{installPostgresCatalog as y}from"./postgres-catalog";async function b(i,e){await y(i),await f(i),await w(i,e);const t=JSON.stringify(e.identity);return e.label===null?await i.prepare(`DELETE FROM __edgepg_security_labels
      WHERE object_type=?1 AND identity_json=?2 AND provider=?3`).bind(e.objectType,t,e.provider).run():await i.prepare(`INSERT INTO __edgepg_security_labels(object_type,identity_json,provider,label,updated_at)
      VALUES (?1,?2,?3,?4,?5)
      ON CONFLICT(object_type,identity_json,provider) DO UPDATE SET
        label=excluded.label,updated_at=excluded.updated_at`).bind(e.objectType,t,e.provider,e.label,new Date().toISOString()).run(),{command:"SECURITY LABEL",rowCount:0}}async function f(i){await i.prepare(`CREATE TABLE IF NOT EXISTS __edgepg_security_labels(
    object_type TEXT NOT NULL,
    identity_json TEXT NOT NULL,
    provider TEXT NOT NULL,
    label TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    PRIMARY KEY(object_type,identity_json,provider))`).run()}async function w(i,e){if(!e.provider)throw new n("42601","SECURITY LABEL requires a provider");if(e.objectType==="OBJECT_SCHEMA"){const t=e.identity.at(-1);if(!t||!await h(i,"__edgepg_schemas",t))throw new n("3F000",`schema "${t||""}" does not exist`,404);return}if(e.objectType==="OBJECT_DATABASE"){const t=e.identity.at(-1)||"";if(!t||!await c(i,"__edgepg_databases","name",t))throw new n("3D000",`database "${t}" does not exist`,404);return}if(e.objectType==="OBJECT_ACCESS_METHOD"){const t=e.identity.at(-1)||"";if(!t||!await c(i,"__edgepg_access_methods","amname",t))throw new n("42704",`access method "${t}" does not exist`,404);return}if(e.objectType==="OBJECT_EVENT_TRIGGER"){const t=e.identity.at(-1)||"";if(!t||!await c(i,"__edgepg_event_triggers","name",t))throw new n("42704",`event trigger "${t}" does not exist`,404);return}if(e.objectType==="OBJECT_COLLATION"){const{schema:t,name:r}=u(e.identity);if(!await E(i,"__edgepg_collations","schema_name",t,"collation_name",r))throw new n("42704",`collation "${s(e.identity)}" does not exist`,404);return}if(e.objectType==="OBJECT_CONVERSION"){const{schema:t,name:r}=u(e.identity);if(!await E(i,"__edgepg_conversions","schema_name",t,"conversion_name",r))throw new n("42704",`conversion "${s(e.identity)}" does not exist`,404);return}if(e.objectType==="OBJECT_TABLE"){const t=p(e.identity);if(!await _(i,t,["table"]))throw new n("42P01",`relation "${s(e.identity)}" does not exist`,404);return}if(e.objectType==="OBJECT_COLUMN"){if(e.identity.length<2)throw new n("42601","SECURITY LABEL ON COLUMN requires a relation and column");const t=e.identity.at(-1),r=e.identity.slice(0,-1),a=p(r);if(!await _(i,a,["table","view"]))throw new n("42P01",`relation "${s(r)}" does not exist`,404);if(!(await i.prepare(`PRAGMA table_info(${T(a)})`).all()).results.some(o=>o.name===t))throw new n("42703",`column "${t}" of relation "${s(r)}" does not exist`,404);return}throw new n("0A000",`SECURITY LABEL ON ${e.objectType.replace(/^OBJECT_/,"").replaceAll("_"," ")} requires an EdgePG object adapter`)}async function c(i,e,t,r){try{return!!await i.prepare(`SELECT 1 AS present FROM ${e} WHERE ${t}=?1`).bind(r).first()}catch(a){if(/no such table/i.test(a instanceof Error?a.message:String(a)))return!1;throw a}}async function E(i,e,t,r,a,l){try{return!!await i.prepare(`SELECT 1 AS present FROM ${e}
      WHERE ${t}=?1 AND ${a}=?2`).bind(r,l).first()}catch(o){if(/no such table/i.test(o instanceof Error?o.message:String(o)))return!1;throw o}}async function _(i,e,t){const r=t.map((a,l)=>`?${l+2}`).join(",");return!!await i.prepare(`SELECT 1 AS present FROM sqlite_master WHERE name=?1 AND type IN (${r})`).bind(e,...t).first()}async function h(i,e,t){try{return!!await i.prepare(`SELECT 1 AS present FROM ${e} WHERE name=?1`).bind(t).first()}catch(r){if(/no such table/i.test(r instanceof Error?r.message:String(r)))return!1;throw r}}function u(i){const e=i.at(-1)||"";return{schema:i.length>1?i.at(-2):"public",name:e}}function s(i){return i.length===1?`public.${i[0]}`:i.slice(-2).join(".")}export{f as ensureSecurityLabelSchema,b as executeSecurityLabelCommand};
