interface TransactionEnv {
    DB: D1Database;
    [binding: string]: unknown;
}
export declare function transactionDdlChangesRelationCatalog(kind: string | undefined): boolean;
export declare function catalogViewBackingTableNames(views: Array<{
    sql: string;
}>, availableTables: ReadonlySet<string>): string[];
export declare function catalogViewDependencyClosure<T extends {
    name: string;
    sql: string;
}>(views: T[], roots: readonly string[]): T[];
export declare class EdgePgTransactionCoordinator {
    private readonly state;
    private readonly env;
    private readonly lockWaiters;
    private lockExpiryTimer?;
    private relationshipEdges?;
    private relationshipEdgesCatalogOnly;
    private relatedTablesByRoot;
    private nativeForeignKeySnapshotsByRoot;
    private readonly snapshotMetadataByTable;
    private readonly constraintFreeTables;
    private readonly constraintFreeTableVersions;
    private readonly constraintMetadataByTable;
    private readonly extensionCastRelationPgTypeCache;
    private extensionCastRelationPgTypeCacheSignature;
    private workspaceCatalogStorageInstalled;
    private activeDatabaseBinding?;
    private activeDatabaseName?;
    private activeDatabaseOwner?;
    constructor(state: DurableObjectState, env: TransactionEnv);
    fetch(request: Request): Promise<Response>;
    private get database();
    private resolveTargetDatabaseBinding;
    private resolveDatabaseIdentity;
    private applyNotifications;
    private pollNotifications;
    private closeNotifications;
    private pruneNotifications;
    private acquireLock;
    private renewLock;
    private releaseLock;
    private cancelLock;
    private promoteLockWaiter;
    private scheduleLockExpiry;
    private clearLockExpiry;
    private expireLock;
    private begin;
    private ensureUsableWorkspace;
    private relationExists;
    private resolveRelations;
    private tableConstraint;
    private fail;
    private role;
    private defaultPrivileges;
    private domainCommand;
    private typeCommand;
    private updateTransactionalEnumState;
    private customTypeCastRewrites;
    private customTypeAccessRewrites;
    private customTypeWriteRewrites;
    private builtinTypeWriteRewrites;
    private transactionUnsafeEnumValues;
    private textSearchCommand;
    private collationCommand;
    private eventTriggerCommand;
    private conversionCommand;
    private prepareEventTriggerCatalog;
    private conversionScalar;
    private prepareConversionCatalog;
    private eventTriggerDispatch;
    private routineCommand;
    private routineRewrites;
    private sequenceCommand;
    private languageCommand;
    private catalogObjectCommand;
    private systemRecordCommand;
    private aggregateCommand;
    private textSearchRewrites;
    private castCommand;
    private operatorCommand;
    private prepareCastCatalog;
    private prepareOperatorCatalog;
    private castRewrites;
    private snapshotCastCatalogs;
    private snapshotOperatorCatalogs;
    private installWorkspaceCastView;
    private installWorkspaceOperatorViews;
    private installWorkspaceTypeView;
    private workspaceTableExists;
    private installWorkspaceCollationView;
    private collationRewrites;
    private reindex;
    private partitionCommand;
    private rowSecurity;
    private rowSecurityCommand;
    private checkPrivileges;
    private comment;
    private securityLabel;
    private canSetRole;
    private canSetSessionAuthorization;
    private checkCursorState;
    private snapshotRoleCatalogs;
    private snapshotTableOwnerAuthorizationCatalogs;
    private snapshotCreateTablePrivilegeCatalogs;
    private schemaPrivilege;
    private databasePrivilege;
    private checkSchemaPrivilege;
    private prepareSchemaIntrospection;
    private schemaCommand;
    private materializedViewCommand;
    private snapshotSchemaWorkspaceCatalogs;
    private snapshotMaterializedViewCatalogs;
    private snapshotWorkspaceTableIndexes;
    private snapshotExistingTables;
    private installWorkspaceConstraintSupportTables;
    private snapshotPgTableCatalog;
    private ensureWorkspaceSchemaObjects;
    private snapshotWorkspaceQueryRelations;
    private applyWorkspacePhysicalRenames;
    private ddl;
    private triggerCommand;
    private snapshotTriggerCatalogs;
    private triggerPrepare;
    private hasTriggerPrograms;
    private triggerState;
    private installWorkspaceTriggers;
    private configureConstraintTriggers;
    private resolveTransactionClusterPlans;
    private installWorkspaceDependencyViews;
    private prepareWorkspaceDependencyBase;
    private installWorkspaceCatalogStorage;
    private ensureWorkspaceObjectCatalogShape;
    private installWorkspaceCatalogs;
    private installMissingWorkspaceCatalogViews;
    private installWorkspaceCatalogDependencyTables;
    private installWorkspaceTextSearchCatalogs;
    private installWorkspaceConversionCatalog;
    private installWorkspaceAggregateView;
    private installWorkspaceRuntimeArtifacts;
    private query;
    private copyRows;
    private installOnConflictUpdateCardinalityGuard;
    private installReturningTransitionCapture;
    private returningTransitionRows;
    private dropReturningTransitionCapture;
    private merge;
    private executeMergeStatementTriggers;
    private prepareMergeSequenceValues;
    private createMergeSource;
    private insertMergeDecisions;
    private validateMergeUsingPolicy;
    private validateMergeSelectNew;
    private mergeActionContexts;
    private attachMergeNewRows;
    private evaluateMergeReturning;
    private evaluateMergeScalarSubquery;
    private executeMergeAction;
    private savepoint;
    private rollbackTo;
    private release;
    private prunePristineWorkspaceSnapshots;
    private flushConstraintTriggerQueue;
    private setConstraints;
    private partitionConstraintClosure;
    private commit;
    private prepareTransaction;
    private commitPrepared;
    private rollbackPrepared;
    private commitSchemaChanges;
    private typeConstraintTriggerSyncStatements;
    private forgetRoleSettingsIfTouched;
    private refreshWorkspaceAnalyzeStatistics;
    private rollback;
    private ensureSchemaFence;
    private renewSchemaFence;
    private releaseSchemaFence;
    private snapshotTable;
    private reusableWorkspaceTable;
    private reusableWorkspaceBaseTable;
    private addSnapshotRows;
    private completeSnapshotRows;
    private mergeSnapshotRows;
    private loadSnapshotRows;
    private committedTableVersion;
    private committedTableVersions;
    private refreshReadCommittedTables;
    private trackCreatedTable;
    private workspaceBigintColumns;
    private applyWorkspaceShapeChanges;
    private loadSnapshot;
    private postgresCatalogPhysicalTableExists;
    private relatedTables;
    private nativeForeignKeySnapshotTables;
    private catalogRelationshipEdges;
    private syncConstraintArtifacts;
    private applyConstraintMetadataCache;
    private loadForeignConstraints;
    private loadUniqueConstraints;
    private loadExclusionConstraints;
    private constraintTableSchemas;
    private reconcileConstraintArtifacts;
    private validateConstraints;
    private validateUniqueConstraints;
    private uniqueConstraintDetail;
    private validateForeignConstraints;
    private tableChanges;
    private commitRowChanges;
    private bulkInsertChange;
    private clear;
    private workspace;
    private requiredWorkspace;
    private usableWorkspace;
}
export {};
